### ISSUE TITLE
Add `--untracked` option to `slide-out`

### ISSUE THREAD

**Issue by PawelLipski** [PawelLipski/git-machete#1051]
Slide out all untracked branches. Replacement for functionality `clean`.

Note that `clean` removes untracked & **childless** branches.
`slide-out --untracked` should slide out (not remove!) branches.
TBD if the condition of childlessness should be retained.

Hmmm removing on the childless branches has the funny side effect: in case of chains of untracked branches, subsequent calls to `slide-out --untracked` will "peel off" the down-most layer 🤔

**Comment by raylu** [comment]
what do you mean by "slide out (not remove!) branches"? doesn't sliding out a branch also delete it locally?

**Comment by PawelLipski** [comment]
`git machete slide-out` only removes branches when `--delete` is passed 🚮 This is mostly due to [the issues with fork point described in FAQ](https://github.com/VirtusLab/git-machete#sometimes-when-i-run-update-or-traverse-too-many-commits-are-taken-into-the-rebase-how-to-fix-that) :/

**Comment by PawelLipski** [comment]
Rel: https://github.com/VirtusLab/git-machete/discussions/1088#discussioncomment-7528103
