### ISSUE TITLE
ubuntu PPA appears to be empty

### ISSUE THREAD

**Issue by raylu** [PawelLipski/git-machete#1053]
# Overview

I noticed #997

## Actual behavior/command output

after `sudo add-apt-repository ppa:virtuslab/git-machete && sudo apt update`,
`apt list \*machete\*` returns nothing

## Expected behavior/command output

`python3-git-machete` is installable

## Platform

    $ dpkg --print-architecture
    arm64
    
    $ cat /etc/issue
    Ubuntu 20.04.6 LTS \n \l

**Comment by PawelLipski** [comment]
Ha! the packages are there: https://launchpad.net/~virtuslab/+archive/ubuntu/git-machete/+packages... but they're only available for `amd64` and not `arm64` ☹️ lemme see what can be done 🤔

**Comment by PawelLipski** [comment]
There shouldn't be really any difference b/w architectures as git-machete is pure-Python, it doesn't contain any architecture-specific code... just a matter of releasing it properly to PPA on our side

**Comment by PawelLipski** [comment]
For the record, this is controlled by a setting in Launchpad itself (not in Debian config files): https://launchpad.net/~virtuslab/+archive/ubuntu/git-machete/+edit

**Comment by PawelLipski** [comment]
Okay v3.18.3 building for [both amd64 & arm64 now](https://launchpad.net/~virtuslab/+archive/ubuntu/git-machete/+packages)...

<img width="1771" alt="image" src="https://github.com/VirtusLab/git-machete/assets/3383210/cdf50ba3-6712-4bd0-b9ae-6961fc6435a6">

**Comment by PawelLipski** [comment]
Okay! they should be published by now, pls check if you can install them now

**Comment by raylu** [comment]
thanks, it works!
