### ISSUE TITLE
Add `--title` option to `create-pr`

### ISSUE THREAD

**Issue by mjgigli** [PawelLipski/git-machete#1092]
# Overview

`create-pr` defaults to using the first commit on the branch as the title for each PR in the stack. The user may want to provide a title (or at least a title prefix, e.g. a Jira ticket number) for created PRs. 

## Expected behavior/command output

When git-machete creates the PR, it could use the argument provided with the `--title` option instead of the commit message of the first commit.

A simpler alternative is to give the user the option to set the PR Title to the branch name.

**Comment by PawelLipski** [comment]
Makes sense! adding right now, to be included in the incoming release...
