### ISSUE TITLE
Add `git machete status` output to PR description or as PR comment when creating or annotating PRs

### ISSUE THREAD

**Issue by mjgigli** [PawelLipski/git-machete#1093]
git-machete already adds a useful prefix to the PR description:

```
# Based on PR #<number of PR for base branch>
```

A very useful extension of this would be to include all of the PRs in the stack, instead of just the parent of this particular PR. I am imagining something similar to the output of `git machete status`, but added to each of the created PRs. It could be added on `git machete github create-pr` and could be updated on `git machete github anno-prs` (or maybe updating this annotation on the PR is it's own subcommand).  Bonus points if the annotation in this included _links_ to the other PRs in the stack!

This idea is inspired by gh-stack: https://github.com/timothyandrew/gh-stack/#examples

**Comment by PawelLipski** [comment]
I've got this idea for some time as well ;) will do!

>  annotation in this included links to the other PRs in the stack!

Rel (albeit it's only about local annotations): #1091, continued at #1096

**Comment by Taiters** [comment]
Is this actively being worked on? If not, I'd be interested in taking a look and raising a PR for this :)

**Comment by PawelLipski** [comment]
Gr8! I've got that in my backlog... but I'm pretty busy with my commercial work recently. I'd appreciate it a lot if open a PR for this <3

**Comment by PawelLipski** [comment]
@Taiters have you started your work? I can help you/pick up from what you've done

**Comment by PawelLipski** [comment]
I've got some free throughput now, lemme implement this one :)

**Comment by PawelLipski** [comment]
Ok... I've cooked up something like that so far:

(https://github.com/PawelLipski/mergify-sandbox/pull/26)

<img width="694" alt="image" src="https://github.com/VirtusLab/git-machete/assets/3383210/3085dde8-d82b-4d09-aee0-81ea80a725ff">

@mjgigli @Taiters lmk if you have any ideas for improvements etc.

**Comment by PawelLipski** [comment]
This is released in v3.23.0. Enabled by default, no extra configuration needed.

**Comment by mjgigli** [comment]
Thank you for this! I think this is super valuable, thanks for knocking it
out.

Matt Gigli
