### ISSUE TITLE
Request: Support using commit message as PR description on github

### ISSUE THREAD

**Issue by kamaradclimber** [PawelLipski/git-machete#1109]
# Overview

When creating a PR using `git machete github create-pr`, the default is to use either `.git/info/description` file or the `.github/template/pull_request.md`.
I think this behavior could be improved by also allowing to take the commit message as source.

Reasoning is:
- `.git/info/description` is a file whose role is not documented anywhere (https://git-scm.com/docs/gitrepository-layout or in the git source code). It is an excellente mechanism to have scripts preparing the PR description
- `.github/template/pull_request.md` is a good way to prepare the PR description prior an edit via the user browser.

To keep the PR creation doable via the terminal only, a third option should be added: using the commit message.

# Proposal

`git machete github create-pr --from-commit-message` would create the PR, adding the first commit of the branch as description (this behavior is consistent with how github populates the PR description when creating a PR from the web UI).

Ideally, this behavior should be the default when none of the two currently used files exist)

...

## `git` and `git machete` versions

```
git --version
git version 2.39.3 (Apple Git-145)

git machete --version
git-machete version 3.20.0
```

**Comment by PawelLipski** [comment]
Makes sense! Tentatively adding to v3.21.0, but I'll probably release that in v3.22.0 (as there's quite a lot of changes waiting for release in v3.21.0).

Actually... 

> git machete github create-pr --from-commit-message

Do you have a use case where you have `.git/info/description` and/or `.github/template/pull_request.md`, but still want to populate the PR description from commit message? If not, I'd rather refrain from adding an extra flag (to keep the CLI somewhat lean), and instead just use the commit message if both these files are absent 🤔

**Comment by kamaradclimber** [comment]
I do have a .github/template/pull_request.md in my repository, but no .git/info/description.
So a flag saying "ignore files and use [default] behavior of looking at first commit of the PR" would be fine as well.

**Comment by PawelLipski** [comment]
One more thing if it comes to the UX... would you rather **always** use the commit message as description, or switch between  `pull_request.md` and commit message on a case-by-case basis? I'm thinking of whether to add a git config key and/or command-line flag 🤔

**Comment by kamaradclimber** [comment]
I think I would prefer a git config key: the behavior would depend on the repository.

**Comment by PawelLipski** [comment]
This is merged to `develop` now, I'll get it released in a couple days. If you'd like to use the `git config machete.github.forceDescriptionFromCommitMessage true` earlier, use `pip install --user .` or `python setup.py install` from this project's directory.

**Comment by kamaradclimber** [comment]
Just tested it, it works as expected (only takes first commit). That’s perfect thanks you!
