### ISSUE TITLE
Add installation method through scoop

### ISSUE THREAD

**Issue by ppasieka** [PawelLipski/git-machete#1183]
On Windows, I find it very handy to use Scoop as a manager for my cli-tools. It would be great to add an option to install the git-machete from it. 

https://scoop.sh/

**Comment by PawelLipski** [comment]
Makes sense! I'll take a look... do you happen to know an existing project that:
1. is a Python app, packaged into Scoop and/or
2. its Scoop package is automatically updated from CI? (or maybe Scoop has a mechanism to update the package automatically? following the package updates in PyPI)

**Comment by PawelLipski** [comment]
Okay, I think I've found two such examples, [Extras -> cookiecutter](https://github.com/ScoopInstaller/Extras/blob/master/bucket/cookiecutter.json) and [Extras -> cruft](https://github.com/ScoopInstaller/Extras/blob/master/bucket/cruft.json)

**Comment by PawelLipski** [comment]
Hmmm AFAICS for main bucket, it must be [_a reasonably well-known and widely used developer tool (e.g. if it's a GitHub project, it should have at least 500 stars and 150 forks)_](https://github.com/ScoopInstaller/Scoop/wiki/Criteria-for-including-apps-in-the-main-bucket). git-machete has ~800 stars at the moment, but only ~40 forks... we'll see how it goes, I'll apply to extras bucket otherwise

**Comment by PawelLipski** [comment]
Steps to follow: https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md#for-scoop-buckets

**Comment by PawelLipski** [comment]
https://github.com/ScoopInstaller/Main/pull/5540

**Comment by ppasieka** [comment]
WOW! @PawelLipski you are super fast! Big 👍

**Comment by PawelLipski** [comment]
Haha at your service/_do usług_... spread the word of this tool! btw how did you learn of git-machete, was it [Ben Congdon's blogpost](https://benjamincongdon.me/blog/2022/07/17/In-Praise-of-Stacked-PRs/)?

**Comment by PawelLipski** [comment]
FYI @ppasieka... it looks that Scoop is generally slow to respond:

<img width="1300" alt="image" src="https://github.com/VirtusLab/git-machete/assets/3383210/d40a327a-ac44-4b96-aca8-3f94987e6ee1">

So it might take a while before this is available ☹️

**Comment by ppasieka** [comment]
@PawelLipski Yeah. I'm guessing they have weekly or bi-weekly sessions to review new packages :) But it is ok.

Back to your previous question on how I found this tool: https://www.youtube.com/watch?v=MxGwryMOKKk I can't remember what led me to this recording.

**Comment by ppasieka** [comment]
@PawelLipski installation with scoop works great! Thanks
