### ISSUE TITLE
`git{hub,lab} restack-{pr,mr}` should first retarget, then push

### ISSUE THREAD

**Issue by PawelLipski** [PawelLipski/git-machete#1222]
Currently it's the other way round: first push, then retarget at the end, for no specific reason.

There seems, however, to be an advantage to the inverse order. In certain CIs (esp. larger corporate ones, with elaborate checks), a push might start a pipeline, and pass the base branch e.g. via env vars, to be consumed by some CI checks. For this case, it's better to first retarget the PR (which is unlikely to start a pipeline), and only then push the branch &mdash; thus triggering the CI pipeline with the right base branch.

**Comment by PawelLipski** [comment]
FYI @raylu (follow-up to #1057)

**Comment by raylu** [comment]
I actually think I'm running into exactly this bug in our CI system. we try and detect the diff by comparing the pushed branch with the base branch (passed via env vars!) and failing because the base branch has been deleted

is anyone working on a fix?

**Comment by PawelLipski** [comment]
Lemme fix it  **n o w**, this should be quick

**Comment by PawelLipski** [comment]
Soon to be released within v3.25.1

**Comment by PawelLipski** [comment]
Actually, v3.25.2, as v3.25.1 partly failed (incl. Homebrew) due to unrelated reasons 🙄
