### ISSUE TITLE
Stop bumping Homebrew formula

### ISSUE THREAD

**Issue by PawelLipski** [PawelLipski/git-machete#1254]
This should be handled by BrewTestBot now that git-machete has been added to [`.github/autobump.txt` in `Homebrew/homebrew-core`](https://github.com/Homebrew/homebrew-core/blob/master/.github/autobump.txt) on [PR #171225 to Homebrew/homebrew-core](https://github.com/Homebrew/homebrew-core/pull/171225/files#diff-895127b46978b016c724afe1fe53341d3d25253eead3b82d796b9bd72aa0c9a9R840).

Let's still check if these updates are correctly performed (preferably, soon after v3.25.3/v3.26.0 release).

**Comment by PawelLipski** [comment]
Yes, a PR got opened 🎉 https://github.com/Homebrew/homebrew-core/pull/172506 

Let's just wait for it to be merged

**Comment by p-linnane** [comment]
@PawelLipski If you would prefer to bump the formula as part of your release process just let me know. I'll remove it from our autobump if that's the case.

**Comment by PawelLipski** [comment]
Quite the opposite, I'd rather have the burden taken away from my CI ;) thanks
