### ISSUE TITLE
Can git machete be used with self signed cert in gitlab?

### ISSUE THREAD

**Issue by scamden** [PawelLipski/git-machete#1300]
I'm getting
```
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)>
```
when using git-machete against our self signed on prem instance of gitlab. I worked around this with `glab` by setting `skip_tls_verify` to `true`

Could git-machete either have it's own setting or honor `http.sslVerify` from the gitconfig?

I think you'd just need to add a little bit of code like: https://stackoverflow.com/a/58337431
to this line: https://github.com/VirtusLab/git-machete/blob/5614a6baf3d708b85d61b8bc29047c83696e10d8/git_machete/gitlab.py#L168

**Comment by PawelLipski** [comment]
Hey, I've just implemented it on https://github.com/VirtusLab/git-machete/pull/1301, I'll get that released soon as v3.27.0 &mdash; pls check if it work correctly for you

**Comment by scamden** [comment]
Yes it worked!! Wow thanks much for the fast turn around! I'm really excited to try machete. I've been dying without my stacked diffs workflow :)

**Comment by PawelLipski** [comment]
Nice to hear :) spread the word!

**Comment by scamden** [comment]
will do! amazing to have a tool like this without hosting provider lock in. i loved graphite, but they are clearly a commercial tool and locked in to github (also it appears this does even more!)

**Comment by PawelLipski** [comment]
Yeah, this is a non-commercial tool and there aren't any plans for monetizing TBH 😅 I've added GitLab support recently, and adding support for yet another hosting provider should be relatively easy if there's a demand
