### ISSUE TITLE
`delete-unmanaged` should detect squash and merged branches

### ISSUE THREAD

**Issue by cinnamennen** [PawelLipski/git-machete#1310]
# Overview

When a PR is merged I can run `traverse` and the branch that was merged in will be slid out. However `delete-unmanaged` will say `unmerged to HEAD` and prompt for confirmation.

## Expected behavior/command output

`delete-unmanaged` should be able to tell that a branch has been squashed and merged.

## Actual behavior/command output

It doesn't.

## `git` and `git machete` versions

```
git --version 2.46.0

git-machete version 3.28.0

```

**Comment by PawelLipski** [comment]
Hmmm makes sense... one thing for clarity, I suppose that `git machete delete-unmanaged --yes` isn't satisfactory for your needs right? as in, you've got some unmanaged branches that you **don't** want to delete?

**Comment by cinnamennen** [comment]
I think that while `--yes` would technically delete the branch I'm not sure I'm comfortable letting it blindly delete in case there was a branch that got slid out and it shouldn't have. 

I've definitely had a few times where while doing some rebase shuffling and reordering of branches machete thought that a branch was unneeded and slid it out (likely due to user error) and I wouldn't want to accidentally delete the branch, even if I could recreate it at the right commit.

**Comment by PawelLipski** [comment]
Ok! I'll get that rectified then

**Comment by PawelLipski** [comment]
To be released soon in v3.29.1
