### ISSUE TITLE
Possible improvement: include the whole stack in PR/MR description with a finger pointing to the current one

### ISSUE THREAD

**Issue by scamden** [PawelLipski/git-machete#1322]
This is a feature I miss from using graphite. Whenever updating a stack of PRs they'd update the annotation on all PR's to include the whole tree, which allowed seamlessly navigating from one to the other. The current PR was bold I think and had a finger emoji pointing to it. A really nice experience. Just a possible suggestion. Thanks again for this awesome open source alternative!

**Comment by scamden** [comment]
I noticed the option to do do machete.gitlab.mrDescriptionIntroStyle:
 "full" but it doesn't seem to show downstream mr's at least not on the root MR in the stack when running `git machete gitlab retarget-mr`

**Comment by PawelLipski** [comment]
Hey, yeah I was about to mention `machete.gitlab.mrDescriptionIntroStyle`... could you describe your case with downstream MRs not showing up in more detail? 🤔 In general, I'd expect downstream MRs to be displayed in the description intro, even for a root MR. Is the repo available publicly maybe?

**Comment by scamden** [comment]
Unfortunately not available publicly. The case is:
I made MR 605 off of `main` and stacked another PR 611 on top of 605 later.
PR 611 shows the great stack comment but nothing on 605. 
I discover mrDescriptionIntroStyle setting and turn it to full:

```
[machete.gitlab]
  mrDescriptionIntroStyle = full
 ```
 
 I run `git machete gitlab retarget-mr`  from branch of 605 which says it updated the MR description, but description of 605 still shows no cool stack comment.
 
Also just tested adding a 3rd PR to the stack and the second PR still doesn't show the 3rd PR downstream in it's description even after retargeting both 2nd and 3rd PR's

I would expect every PR in the stack to have a description with all of the up and downstream PR's

**Comment by PawelLipski** [comment]
Hmmm okay and a sanity check: what's your `git machete version`?

**Comment by milescrabill** [comment]
This was fixed for me by updating to the latest version. I was a little confused at first because the version installed via Homebrew on macOS was not up-to-date.

I was able to update to the latest version using `brew reinstall --build-from-source git-machete`.

**Comment by scamden** [comment]
here's mine: git-machete version 3.28.0

and yes i also installed with brew!

**Comment by PawelLipski** [comment]
> here's mine: git-machete version 3.28.0

Whoops yeah, the feature you're looking for has only been added in [v3.29.0](https://github.com/VirtusLab/git-machete/releases/tag/v3.29.0), pls update 😅 

> I was able to update to the latest version using brew reinstall --build-from-source git-machete.

This is unexpected, I'm gonna check why `brew upgrade` didn't/doesn't work for git-machete formula 🤔

**Comment by PawelLipski** [comment]
Actually... @scamden I'd appreciate if you send your current `brew info git-machete`, then run `brew upgrade git-machete` and again pls include `brew info git-machete`. I tried upgrading Brew-installed git-machete locally and didn't see any problems... I'd better to know if there're any, given that Homebrew is our most popular installation channel 🤔

**Comment by scamden** [comment]
happy to! looks like for me the upgrade worked! sorry didn't think to try this originally :) 

```
==> git-machete: stable 3.28.0 (bottled)
Git repository organizer & rebase workflow automation tool
https://github.com/VirtusLab/git-machete
Installed
/opt/homebrew/Cellar/git-machete/3.28.0 (58 files, 1.2MB) *
  Poured from bottle using the formulae.brew.sh API on 2024-08-21 at 12:04:26
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/g/git-machete.rb
License: MIT
==> Dependencies
Required: python@3.12 ✔
==> Caveats
zsh functions have been installed to:
  /opt/homebrew/share/zsh/site-functions
==> Analytics
install: 324 (30 days), 821 (90 days), 2,720 (365 days)
install-on-request: 324 (30 days), 821 (90 days), 2,720 (365 days)
build-error: 0 (30 days)
```

```
==> git-machete: stable 3.29.2 (bottled)
Git repository organizer & rebase workflow automation tool
https://github.com/VirtusLab/git-machete
Installed
/opt/homebrew/Cellar/git-machete/3.29.2 (42 files, 797.2KB) *
  Poured from bottle using the formulae.brew.sh API on 2024-09-12 at 07:36:03
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/g/git-machete.rb
License: MIT
==> Dependencies
Required: python@3.12 ✘
==> Caveats
zsh functions have been installed to:
  /opt/homebrew/share/zsh/site-functions
==> Analytics
install: 324 (30 days), 821 (90 days), 2,720 (365 days)
install-on-request: 324 (30 days), 821 (90 days), 2,720 (365 days)
build-error: 0 (30 days)
```

**Comment by PawelLipski** [comment]
Okay! so I'm assuming this is resolved ;)

**Comment by scamden** [comment]
yep it's fixed! thanks great feature!

**Comment by scamden** [comment]
maybe this is already known somewhere, but one nice addition would be to update other MR's when creating or retargeting one. Right now if I add a downstream MR it seems i have to go update all the other ones in the stack to get their descriptions to show it

**Comment by PawelLipski** [comment]
There's a related feature in the working queue: https://github.com/VirtusLab/git-machete/issues/1215, but this is about retargeting PRs and updating their description as `traverse` walks the branches. Still, a flag like `--update-all-descriptions` to `{create,restack,retarget}-pr` would be useful, lemme open an issue
