### ISSUE TITLE
Split `test_machete.py` into command-specific test files (`test_github.py`, `test_show.py` etc.)

### ISSUE THREAD

**Issue by PawelLipski** [PawelLipski/git-machete#232]

**Comment by AABur** [comment]
I like to implement this task.

But first, I suggest connecting [Codecov](https://about.codecov.io/) to control code coverage by tests.
CircleCI doesn't provide the ability to control code coverage. 
The connection of Codecov is straightforward with GitHub Actions.
You can see the result in my [fork](https://github.com/AABur/git-machete/tree/develop). An appropriate `badge` is added there. Here you can see what [Codecov Report](https://github.com/AABur/git-machete/pull/3#issuecomment-1100237043) looks like.

Firstly, it will avoid breaking or losing some of the tests.
Secondly, it will be easy to control the coverage of the code by the tests in future updates.

**Comment by PawelLipski** [comment]
Wow I see your fork, nice 🚀 

Actually, we've got _some_ automation for code coverage: `coverage` results are upload as artifacts on each CircleCI build, you can check e.g. [latest develop build's Artifacts](https://app.circleci.com/pipelines/github/VirtusLab/git-machete/1855/workflows/eb949dbb-6996-4586-a350-7165f7110970/jobs/8312/artifacts) -> [coverage/index.html](https://output.circle-artifacts.com/output/job/b7de3a97-2d6c-42c0-ac0a-0d9edb219188/artifacts/0/coverage/index.html)

But Codecov is much smoother indeed. Would you mind opening a pull request from your fork?

Also! how did you learn about this project, was it via [goodfirstissues.com](https://goodfirstissues.com/) ?

**Comment by AABur** [comment]
Regarding CircleCI, I understand how it is realised. But it's nothing more than the storage of a coverage report. And it's not clear at all. Codecov provides code coverage checks that are more straightforward and transparent. Especially for Pull Request.

Yes! I found this project on [goodfirstissues.com](https://goodfirstissues.com/).

**Comment by PawelLipski** [comment]
Okay! feel free to proceed with a PR

**Comment by AABur** [comment]
TODO:

- [x] refactor `test_machete.py` in **pytest** style -> DONE #498 

- [x] move common classes and  functions into separate module -> DONE #500

split `test_machete.py` into command-specific test files
- [x] add #502 
- [x] advance #512
- [ ] anno
- [x] clean #503
- [ ] delete-unmanaged
- [ ] diff
- [ ] discover
- [ ] edit
- [ ] file
- [ ] fork-point
- [ ] format
- [x] github #505 
- [x] go #513
- [x] help #503
- [ ] hooks
- [ ] is-managed
- [ ] list
- [x] log #503
- [ ] reapply
- [x] show #507
- [x] slide-out #504 
- [x] squash #504 
- [x] status #514
- [x] traverse #514
- [x] update #501 
- [ ] version

**Comment by AABur** [comment]
@PawelLipski step2 done at #500 
The remaining mock functions in test_machete.py are specific to testing individual commands

**Comment by AABur** [comment]
@PawelLipski assign me to this issue

**Comment by AABur** [comment]
Tests are currently too deep in the directory tree

```
git_machete/git_machete
├── __init__.py
├── cli.py
├── client.py
├── constants.py
├── docs.py
├── exceptions.py
├── git_operations.py
├── github.py
├── options.py
├── tests
│   ├── __init__.py
│   └── functional
│       ├── __init__.py
│       ├── mockers.py
│       ├── test_add.py
│       ├── test_advance.py
│       ├── test_clean.py
│       ├── test_github.py
│       ├── test_go.py
│       ├── test_help.py
│       ├── test_log.py
│       ├── test_show.py
│       ├── test_slide_out.py
│       ├── test_squash.py
│       ├── test_status.py
│       ├── test_traverse.py
│       └── test_update.py
└── utils.py
```

My suggestion:
1. remove the directory `functional` and put all tests in the directory `tests`
2. move the `tests` directory up one level
```
git_machete/git_machete
├── __init__.py
├── cli.py
├── client.py
├── constants.py
├── docs.py
├── exceptions.py
├── git_operations.py
├── github.py
├── options.py
└── utils.py

git_machete/tests
├── __init__.py
├── mockers.py
├── test_add.py
├── test_advance.py
├── test_clean.py
├── test_github.py
├── test_go.py
├── test_help.py
├── test_log.py
├── test_show.py
├── test_slide_out.py
├── test_squash.py
├── test_status.py
├── test_traverse.py
└── test_update.py
```

The import of common functions/methods in tests will become shorter and easier to understand.
Tests will not be saved with the application code.

**Comment by PawelLipski** [comment]
> Tests are currently too deep in the directory tree

+1, good idea &mdash; pls proceed!

**Comment by AABur** [comment]
I think this issue can be closed.
There is still room for improvement. I will do this little by a bit while solving other test-related issues.
