### ISSUE TITLE
`git fetch` should probably be executed with `--prune` in all contexts

### ISSUE THREAD

**Issue by PawelLipski** [PawelLipski/git-machete#243]
Like `traverse` or `github checkout-prs`.

Rationale: if a branch is deleted on a remote repo (like, when its corresponding PR has been merged), the easiest way to know it is when your local "mirror" under `.git/refs/remotes/<remote>/...` gets removed. This is NOT a default behavior of `git fetch`, though &mdash; `--prune` flag needs to be passed.

**Comment by rifel123** [comment]
closed with #267
