### ISSUE TITLE
There should be no calls to `run_git` or `popen_git` from client.py

### ISSUE THREAD

**Issue by PawelLipski** [PawelLipski/git-machete#251]
Instead, `MacheteClient` should use dedicated methods from `GitContext` and never interact with `git` binary directly.

This is important not only for clean-code reasons, but also for correctness: `GitContext` maintains caches which might be invalidated by side-effecting `git` operations (like `checkout` or `reset` &mdash; anything that modifies the repo).

**Comment by PawelLipski** [comment]
As @BartoszSiwinski noted, there's clearly at least one bug, around `delete_unmanaged`: https://github.com/VirtusLab/git-machete/pull/249#discussion_r715554832

**Comment by BartoszSiwinski** [comment]
As part of this story, cache invalidation/clearing should be reconsidered.
