### ISSUE TITLE
Add more files to `tar-ignore` under `debian/options/source`

### ISSUE THREAD

**Issue by PawelLipski** [PawelLipski/git-machete#276]
See https://launchpad.net/~virtuslab/+archive/ubuntu/git-machete/+sourcefiles/python3-git-machete/3.4.0~18.04/python3-git-machete_3.4.0~18.04.tar.gz: surely `blogs`, `graphics` and `mypy.ini` should be excluded (logo.png can be un-excluded then)

**Comment by rifel123** [comment]
Closed with #307
