### ISSUE TITLE
A way to mark branches that should not be rebased and/or pushed during `traverse`

### ISSUE THREAD

**Issue by PawelLipski** [PawelLipski/git-machete#293]
As a follow-up to #292.

Certain branches should never be rebased or pushed within `traverse`. See https://github.com/VirtusLab/git-machete/issues/656 for discussion.

TBD how this marking should be expressed in .git/machete (branch name preceded with some symbol prohibited in git branch names?)

TBD if low-level operations like `advance`/`reapply`/`squash`/`update` should be limited (I'd say **no**).

`github anno-prs` and `github checkout-prs` could also support marking the branches as such by default.

TODO:

- [ ] Add qualifiers ( rebase/push=no/yes, read-only) that control behaviour of `traverse`
- [ ] Add tests
- [ ] Prevent commands: `discover, github anno-prs, github checkout-prs` (check if there are more commands that can modify annotation) from modifying qualifiers except command `github checkout-prs` that adds `read-only` qualifier for the branch associated with the PR that is assigned to someone else

**Comment by PawelLipski** [comment]
Rationale: I've accidentally rebased & pushed teammate's branches that I've checked out just for a review 🤦🏻

**Comment by PawelLipski** [comment]
> TBD how this marking should be expressed in .git/machete (branch name preceded with some symbol prohibited in git branch names?)

Or better! without breaking compatibility: just recognize certain prefix/suffix of custom annotation like `rebase=no` or `do-not-modify` or `read-only`... backward-compatible and much clearer than some magic symbols. This part of custom annotation will be only interpreted by later versions of git-machete; earlier versions will just display it as a part of the annotation, which is probably acceptable

Or yet another way, even more lightweight: let a user define a regex in git config key that would match custom annotations for such branches. E.g. `PR #.* \(.*\)` => this matches custom annotations written by `git machete github anno-prs/checkout-prs` where the author is NOT the current GitHub user.

**Comment by amalota** [comment]
Alright, so to sum up i see there are 3 proposed solutions:
1. Modifying .git/machete
 - ugly branch names
 - modifying branch names can get tricky and unpleasant
 - more time consuming than no. 2.
2. Modifying branch annotation
 - best solution IMO
 - most robust, solves rebase/push/* for each user
 - easy but would require new subcommand `anno add` that would add annotation text at the end of the existing annotation text
3. Config key with regex that would parse branch annotation to find branches where author is NOT the current github user.
 - only partial solution

@PawelLipski, wdyt? Do you also agree that no. 2 is the best solution? If so can you emphasise this issue, it's not super clear for me:

> This part of custom annotation will be only interpreted by later versions of git-machete; earlier versions will just display it as a part of the annotation, which is probably acceptable

**Comment by PawelLipski** [comment]
LGTM for option 2️⃣ indeed!

I think `git machete anno add` (adding a subcommand to `anno` which didn't have subcommands so far) isn't the good direction. I'd generally just make `anno` ignore the `rebase=no` (or whatever it ends up called) part in all (?) contexts.

> This part of custom annotation will be only interpreted by later versions of git-machete; earlier versions will just display it as a part of the annotation, which is probably acceptable

Assuming .git/machete looks like

```
main
  foo rebase=no PR #1234
```

old git-machete versions will display status:

```
main
|
o-foo   rebase=no PR #1234
```

while the newer version will interpret `rebase=no` (or again, however we end up calling it) as special directive and display just

```
main
|
o-foo   PR #1234
```

**Comment by amalota** [comment]
@PawelLipski I would actually not hide the `rebase=no` annotation since it can be pretty easily forgotten and it doesn't actually look bad IMHO. 

Also `git machete anno add` would be useful if you already have some annotation and don't want either edit manually machete file with `edit` or replace whole annotation with `anno` as it would add annotation to the end.

**Comment by amalota** [comment]
Firstly, we need to fix present annotations overwriting by `discover` -> https://github.com/VirtusLab/git-machete/issues/547 which would terribly mess with this PR.
Also, `github checkout-prs/anno-prs` both overwrite the annotations too. Although i agree that their main use is to fetch prs for the first time but it also modifies already checked-out PR and resets their annotations as well. I would for example as some check which would ensure that it doesn't modify annotations for already checked-out PRs, @PawelLipski wdyt? -> https://github.com/VirtusLab/git-machete/issues/717

**Comment by amalota** [comment]
Regarding prefixes, which functions do we want to control - push and rebase only as suggested? 
if so, does `push/rebase=no/yes` sound sufficient? There also might be some use cases for `read-only` -> `checkout-prs`, i'm up to add it as well.

Regarding:

> TBD if low-level operations like advance/reapply/squash/update should be limited (I'd say no).

I agree.

Regarding:

> github anno-prs and github checkout-prs could also support marking the branches as such by default.

I definitely think that `github checkout-prs` can add by default `read-only` annotation for the PR's which are assigned to sb else (#717 would ensure that `read-only` won't get written multiple times). I am not sure about `anno-prs` though, but i don't see any harm in it doing so - assuming same restrictions as  `github checkout-prs`.

**Comment by PawelLipski** [comment]
>  Although i agree that their main use is to fetch prs for the first time but it also modifies already checked-out PR and resets their annotations as well. I would for example as some check which would ensure that it doesn't modify annotations for already checked-out PRs,

They could also just retain the `rebase/push=no/yes` parts and overwrite overwrite everything else... TBD

**Comment by PawelLipski** [comment]
> Regarding prefixes, which functions do we want to control - push and rebase only as suggested?

Yes, so far I can see no use case for blocking a pull or slide-out.

> if so, does push/rebase=no/yes sound sufficient?

Let's stick to that as for now.

>  There also might be some use cases for read-only -> checkout-prs, i'm up to add it as well.

Would `read-only` just mean the same as `rebase=no` together with `push=no`?

**Comment by amalota** [comment]
@PawelLipski Yes it would, just shorter i guess

**Comment by PawelLipski** [comment]
Ok, let's go for that as for now

**Comment by PawelLipski** [comment]
As agreed, operations that modify/delete/overwrite custom annotations like `discover`, `github anno-prs`, `github checkout-prs` etc. should all leave the `rebase=no`/`read-only` stuff untouched.

Let's call that stuff **qualifiers** btw.
