### ISSUE TITLE
`__tree_sha_by_commit_sha_cached` doesn't ever need to be flushed

### ISSUE THREAD

**Issue by PawelLipski** [PawelLipski/git-machete#311]
Thanks to git immutability guarantees, we don't need to worry about a tree hash changing for a commit of the given hash ;)
The same point applies to e.g. `__merge_base_cached` and `__contains_equivalent_tree_cached`. TBD what else.

These caches never need to be flushed. Once an entry is saved, it doesn't make sense to remove it (unlike with e.g. `__commit_sha_by_revision_cached` which is prone to getting outdated over time, as branches can be repointed to different commits).

**Comment by rifel123** [comment]
closed with #338
