### ISSUE TITLE
Is `yq` installation in CI config still needed?

### ISSUE THREAD

**Issue by PawelLipski** [PawelLipski/git-machete#312]
We do install `yq`... but only in the `initial checks` job, where `yq` is **not** used AFAICS.

`yq` is in turn used in the other jobs (in `ci/docker-build-and-push.sh`)... but `yq` isn't getting explicitly installed within these jobs.

I suspect `yq` is already included in the Ubuntu VM we're using... let's research that remove the explicit install from CI config if possible.

**Comment by rifel123** [comment]
closed with #352
