### ISSUE TITLE
In `github checkout-pr`, remote is NOT being fetched if a remote branch already exists locally... but is it the best UX?

### ISSUE THREAD

**Issue by PawelLipski** [PawelLipski/git-machete#313]
Lemme explain on an example of PR #302... I've got an `origin/fix/help` branch pointing to `910f685`, and did NOT have local `fix/help` branch.

As I fired `git machete github checkout-prs 302`, the following actions have been done:

```
A local branch fix/help does not exist, but a remote branch origin/fix/help exists.
Checking out fix/help locally...
Branch 'fix/help' set up to track remote branch 'fix/help' from 'origin'.
Switched to a new branch 'fix/help'
Added branch fix/help onto develop
Annotating fix/help as PR #302 (BartoszSiwinski)
Pull request #302 checked out at local branch fix/help
```

Most notably, `origin` remote has NOT been fetched.

Now I've got `fix/help` shown as in sync with remote:

![image](https://user-images.githubusercontent.com/3383210/138710116-f633c7e5-af9c-4ffa-baee-34bd3753ad14.png)

which is technically true (as in, `fix/help` and `origin/fix/help` point to the same commit in my local repo)... but that's NOT really what I would expect. Once I've done a `git fetch`:

```
.......
From github.com:VirtusLab/git-machete
 + 910f685...d81b911 fix/help         -> origin/fix/help  (forced update)
   9f7c896..d60036d  build/tar-ignore -> origin/build/tar-ignore
   152ce77..e37f8d8  develop          -> origin/develop
```

the branch is marked as diverged from remote:

![image](https://user-images.githubusercontent.com/3383210/138710619-cd338ca6-73e1-4a63-bf6c-ccee3d6043c2.png)

After doing `git machete github checkout-prs 302`, I'd rather have at least the info (shown as usual, in `git machete status` and `git status`) that `fix/help` diverged from origin. Up to me then whether I leave it diverged or do some `git reset --keep @{upstream}` manually/via `git machete traverse`.

**So, action point: consider doing `git fetch` for the relevant remotes always when checking out a PR**, no exception for the case when a remote branch already exists locally in `.git/refs/remotes/`

**Comment by rifel123** [comment]
closed with #327
