### ISSUE TITLE
Unify the usage of `sha` vs `hash` in code

### ISSUE THREAD

**Issue by PawelLipski** [PawelLipski/git-machete#319]
I'd vote for `hash`, but that's mostly a matter of taste, both are pretty clear

**Comment by mohitsaxenaknoldus** [comment]
By "Unify" do you mean only using one of them throughout?

**Comment by PawelLipski** [comment]
Oh, hello back :) yes, exactly, there're currently a lot of usages of `hash` and `sha`, with no real reason behind picking one vs another... let's use only one of these **e v e r y w h e r e**!

**Comment by mohitsaxenaknoldus** [comment]
any preference?

**Comment by PawelLipski** [comment]
I'd go for `hash` #️⃣

**Comment by mohitsaxenaknoldus** [comment]
Ok, assign me.

**Comment by PawelLipski** [comment]
Hey @mohitsaxenaknoldus... how's going?

**Comment by PawelLipski** [comment]
Coz we're about to cut a release soon-ish (to include the recent @jiyap's fix https://github.com/VirtusLab/git-machete/pull/349)

**Comment by mohitsaxenaknoldus** [comment]
> Coz we're about to cut a release soon-ish (to include the recent @Jiyap's fix #349)

When is the release?

**Comment by PawelLipski** [comment]
If you're able to do the refactors soon, we can cut the release once you done... but ofc we can as well cut the release without them and they'll go into the subsequent release (3.5.2 or 3.6.0), up to you :)

**Comment by AABur** [comment]
@PawelLipski can you clarify what you mean. I found the use of `sha` only in variable names. So mass replacement of `sha` with `hash` can be done - nothing will change in principle in the code.

**Comment by PawelLipski** [comment]
Right, that's exactly what I mean... just renaming variables/methods for consistency
