### ISSUE TITLE
Document local installation for development purposes in CONTRIBUTING.md

### ISSUE THREAD

**Issue by PawelLipski** [PawelLipski/git-machete#324]
As for now I was using `python setup.py install`... but thanks to @BartoszSiwinski I realized that it could be done with `pip install -e .`. Let's research upsides and downsides of each and decide as to which one (maybe both?) to put in our guidelines.

**Comment by rifel123** [comment]
For testing purposes, just to make sure i am testing right version, i change `version` in `__init__.py` a little bit and this time i installed it with `pip install -e .`. When I got back to develop branch, without installing version from develop i faced version error:
<img width="972" alt="Screenshot 2021-10-28 at 14 43 41" src="https://user-images.githubusercontent.com/73847352/139258490-6d39587b-66bf-4670-93d9-904bcfd96a0e.png">

I am not sure but it seems like `pip install -e .` sources files from given directory also after installation, TBD if it's true.

About version check, i think it's ok, as it limits chance to use wrong version. Also after new release, update of git-machete will be enforced :)

**Comment by PawelLipski** [comment]
Probably `pip install -e .` is better indeed than `python setup.py install`, see https://pip.pypa.io/en/stable/topics/local-project-installs/

**Comment by PawelLipski** [comment]
Let's also figure out whether for development purposes, `pip install -e .` should be against venv created via `tox -e venv`, or rather it should be `pip install --user` (with files installed in `~/.local/`).

**Comment by amalota** [comment]
IMO `pip install -e .` in the venv is the cleanest option.
