### ISSUE TITLE
Add fish completion to NixOS package definition

### ISSUE THREAD

**Issue by PawelLipski** [PawelLipski/git-machete#337]
See https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/version-management/git-and-tools/git-machete/default.nix#L31

To be tested locally (or within a Docker container) first.

**Comment by rifel123** [comment]
After building locally nix package of git-machete and testing it in docker image `nixos/nix:2.3.6` the results are not so promising. Installing completion scripts directly from nix package doesn't work automatically for zsh, bash and fish. I have also put `git-lfs` and 'hub' under similar tests and completion worked fine only for `hub` and only within fish shell.

**Comment by PawelLipski** [comment]
☹️ closing the issue then as `won't fix`
