### ISSUE TITLE
Unify error message handling from `UnprocessableEntityError`

### ISSUE THREAD

**Issue by rifel123** [PawelLipski/git-machete#345]
When Github API returns status code 422, the data can be served on 3 ways (3 shapes of response was observed):
- in case of adding reviewers from outside organisation:
`{'message': 'Reviews may only be requested from collaborators. One or more of the users or teams you specified is not a collaborator of the rifel123/sandbox repository.', 'documentation_url': 'https://docs.github.com/rest/reference/pulls#request-reviewers-for-a-pull-request'}`
- in case of creating pull request which already exists:
`{'message': 'Validation Failed', 'errors': [{'resource': 'PullRequest', 'code': 'custom', 'message': 'A pull request already exists for rifel123:new_branch.'}], 'documentation_url': 'https://docs.github.com/rest/reference/pulls#create-a-pull-request'}`
- in case when base branch for PR does not exists on remote:
`{'message': 'Validation Failed', 'errors': [{'resource': 'PullRequest', 'field': 'base', 'code': 'invalid'}], 'documentation_url': 'https://docs.github.com/rest/reference/pulls#create-a-pull-request'}`
- in case of creating a PR with base branch equal to head branch:
`{'message': 'Validation Failed', 'errors': [{'resource': 'PullRequest', 'code': 'custom', 'message': 'No commits between develop and same'}], 'documentation_url': 'https://docs.github.com/rest/reference/pulls#create-a-pull-request'}`

Currently only second and fourth option is covered. Question is rather what to do when no relevant info is available, like in third response? Maybe just print out all response? TBD

**Comment by PawelLipski** [comment]
I love getting (and providing myself) breakdowns like the above <3

Yeah, in the unfortunate 3. case, let's just print whatever we've got (the entire JSON).
The level of (in)consistency in the Github API errors is disappointing btw :/

**Comment by rifel123** [comment]
closed with #346
