### ISSUE TITLE
`GitRepositorySandbox.new_repo` has a side effect of changing the current directory

### ISSUE THREAD

**Issue by PawelLipski** [PawelLipski/git-machete#362]
```python
    def new_repo(self, *args: str) -> "GitRepositorySandbox":
        os.chdir(args[0])
        opts = args[1:]
        self.execute(f"git init {' '.join(opts)}")
        return self
```

Some `os.chdir` back to the original position would be useful here... or, if the current behavior makes more sense, maybe a rename to this method?

**Comment by PawelLipski** [comment]
TBD if it's still a problem... might be outdated by now

**Comment by amalota** [comment]
> TBD if it's still a problem... might be outdated by now

@PawelLipski It is up to date, i bumped into this issue recently and i have to say that the current behaviour didn't make much sense in the tests that i was writing so i am all for the solution to `os.chdir` back to the original position.

**Comment by amalota** [comment]
@PawelLipski Hmm, not sure if it is worth doing, after changing the behaviour all the tests failed :D it looks like current behaviour is more than expected in the each test's `setup_method`

```
    def setup_method(self) -> None:
    
        self.repo_sandbox = GitRepositorySandbox()
    
        (
            self.repo_sandbox
            # Create the remote and sandbox repos, chdir into sandbox repo
            .new_repo(self.repo_sandbox.remote_path, "--bare")
            .new_repo(self.repo_sandbox.local_path)
>           .execute(f"git remote add origin {self.repo_sandbox.remote_path}")
            .execute('git config user.email "tester@test.com"')
            .execute('git config user.name "Tester Test"')
        )
```

**Comment by amalota** [comment]
Maybe just adding a flag to the function: `switch_dir_to_new_repo` that defaults to True would solve the issue (not needing to change the dir manually) and be compatible with current tests?

**Comment by PawelLipski** [comment]
Okay! flag sounds like a good idea indeed, at least it's gonna be clear what the behavior wrt. changing the directory is
