### ISSUE TITLE
Subtask of #552: `github create-pr` doesn't take branch tracking data into account

### ISSUE THREAD

**Issue by PawelLipski** [PawelLipski/git-machete#372]
I've got two remetes `foo` and `bar`, both of which correspond to Github &mdash; neither is called `origin`.

I've got a branch called `qux` which I've pushed to `bar` (`git push -u bar qux`).

Now when running `git machete github create-pr` while on `qux`, I'd expect the PR to opened against `bar` repo, but instead I'm getting:

`Multiple non-origin remotes correspond to GitHub in this repository: foo, bar, aborting`

This message would make sense only if `qux` was NOT yet pushed to any of these repos.

**Comment by PawelLipski** [comment]
This might've been resolved already, or the behavior might've changed... pls check

**Comment by amalota** [comment]
> This might've been resolved already, or the behavior might've changed... pls check

Ok, will do

**Comment by amalota** [comment]
@PawelLipski Can confirm that this bug is still present

**Comment by PawelLipski** [comment]
> Can confirm that this bug is still present

As in, `Can you` or `I can`? 👅

**Comment by amalota** [comment]
> > Can confirm that this bug is still present
> 
> As in, `Can you` or `I can`? 👅

As in, i already checked and can confirm that the bug is still present, although this time the message has additional line which presents solution to the problem but you have to do it manually and branch tracking data would still not be taken into account. 


```
Multiple non-origin remotes correspond to GitHub in this repository: repo, repo2, aborting.
You can also select the repository by providing 3 git config keys: machete.github.{remote,organization,repository}
```

I would say that the solution is not perfect and we should implement the new logic since we can eliminate the need to do anything manually. @PawelLipski wdyt?

**Comment by PawelLipski** [comment]
+1, let's still proceed.

Also, nit:

```
Multiple non-origin remotes correspond to GitHub in this repository: repo, repo2, aborting.
```

this looks weird xD a semicolon after the last remote would be better, like
```
Multiple non-origin remotes correspond to GitHub in this repository: repo, repo2; aborting.
```

**Comment by amalota** [comment]
Also, i realised that similar problem where there are multiple remotes (none of them `origin`) exist not only for `create-pr` subcommand but also for:
- anno-prs (from which repo choose the annotations from when both remotes have two PR-s with the same branch name),
- checkout-prs (which branch to checkout when both remotes have two PR-s with the same branch name)
- sync (with which remote to synchronise)
- retarget-prs (not sure yet what could go wrong here)
- 
I guess this issue might be bigger than just `create-pr`, @PawelLipski WDYT? Should i create parent issue for problems regarding multiple remotes and then child issues for each subcommand?

**Comment by PawelLipski** [comment]
> Should i create parent issue for problems regarding multiple remotes and then child issues for each subcommand?

Good idea indeed... there's no _parent/child issue_ formally within GitHub, but let's simulate e.g. with `[subtask of #...]` title prefix or whatnot

**Comment by PawelLipski** [comment]
Crap, that was a bad idea 🤦🏻 lemme elaborate on another PR...
