### ISSUE TITLE
Add ability to pass extra arguments to git-rebase

### ISSUE THREAD

**Issue by kgadek** [PawelLipski/git-machete#376]
# Overview

Feature request.
When doing `git machete traverse`, seldom I'd like to be able to pass extra flags to git-rebase, e.g. `-Xignore-all-space --rebase-merges`.

## Example use case

I'm batching multiple smaller PRs. By preserving merges in the history, I'm able to auto-close PRs on GitHub. In order to do that, I need `--rebase-merges` flag.

**Comment by kgadek** [comment]
As a comment, I don't have any preference _how_ to do that. I can think of _at least_ those:
- `env GITMACHETE_REBASE_FLAGS="-Xignore-all-space --rebase-merges" git machete traverse`
- `git machete traverse -- -Xignore-all-space --rebase-merges`
- `git machete traverse --rebase-flags="-Xignore-all-space --rebase-merges"`.

**Comment by PawelLipski** [comment]
After some consideration, I'd go for the first suggested option (`GIT_MACHETE_REBASE_FLAGS`) &mdash; to avoid polluting the already cluttered CLI for `traverse`. Also, options passed to rebase tend to be more of a global/repeatable (as opposed to one-off/per-command) config &mdash; for which case an env var is a better fit.

I'll release 3.6.2 to wrap up the changes contributed by @mohitsaxenaknoldus, and then include this feature in subsequent 3.7.0 release.

**Comment by PawelLipski** [comment]
Closed, soon to be released in v3.7.0
