### ISSUE TITLE
Upload test results for viewing in CI

### ISSUE THREAD

**Issue by PawelLipski** [PawelLipski/git-machete#378]
https://circleci.com/docs/2.0/configuration-reference/#storetestresults

**Comment by mohitsaxenaknoldus** [comment]
I can work on this.

**Comment by PawelLipski** [comment]
Okay! great, should be relatively quick

**Comment by mohitsaxenaknoldus** [comment]
BTW, the CI tests or the normal tests?

**Comment by PawelLipski** [comment]
The regular tests executed by `tox`!

**Comment by PawelLipski** [comment]
But executed in the CI

**Comment by mohitsaxenaknoldus** [comment]
This one right?: https://github.com/VirtusLab/git-machete/blob/05671cfe8d778c70a9db4d427566cdd0cfad2901/ci/tox/ci-run.sh

**Comment by PawelLipski** [comment]
Yes, exactly

**Comment by mohitsaxenaknoldus** [comment]
So, is this already producing the output somewhere?

**Comment by PawelLipski** [comment]
I'm not sure about whether it produces output in the format that will be understood by circle CI... pls research! I suppose this might be a matter of some config in tox.ini.
Also, you can use ci/tox/local-run.sh locally

**Comment by mohitsaxenaknoldus** [comment]
I am on a new laptop and looks like I lost all my previous setup for this project :(
`Var GIT_VERSION missing from environment and no .env file found; see .env.sample file`

**Comment by PawelLipski** [comment]
Pls just copy .env.sample to .env in the same ci/tox directory

**Comment by mohitsaxenaknoldus** [comment]
Where is that file?

**Comment by PawelLipski** [comment]
ci/tox!

**Comment by mohitsaxenaknoldus** [comment]
I was able to produce a json file containing the tests results but I don't understand how [this file](https://github.com/VirtusLab/git-machete/blob/05671cfe8d778c70a9db4d427566cdd0cfad2901/ci/tox/ci-run.sh) is running the tests?

**Comment by PawelLipski** [comment]
Oh! the exact line that runs the tests in that script is `docker-compose --ansi never run tox`... you can find out more about the entire CI pipeline design in the blogposts linked from https://github.com/VirtusLab/git-machete/blob/master/CONTRIBUTING.md#ci-docker-setup-reference

**Comment by PawelLipski** [comment]
What's the exact format of the test results? can you post a sample? was a change to source code needed to get this JSON generated?

**Comment by mohitsaxenaknoldus** [comment]
`{
  "reportversion": "1",
  "toxversion": "3.13.2",
  "platform": "linux",
  "host": "knoldus-Latitude-3520",
  "commands": [],
  "testenvs": {
    "pep8": {
      "setup": [
        {
          "command": [
            "/usr/bin/python3",
            "-m",
            "virtualenv",
            "--no-download",
            "--python",
            "/usr/bin/python3",
            "pep8"
          ],
          "output": "created virtual environment CPython3.8.10.final.0-64 in 110ms\n  creator CPython3Posix(dest=/home/knoldus/OS/git-machete/.tox/pep8, clear=False, global=False)\n  seeder FromAppData(download=False, pip=latest, setuptools=latest, wheel=latest, pkg_resources=latest, via=copy, app_data_dir=/home/knoldus/.local/share/virtualenv/seed-app-data/v1.0.1.debian.1)\n  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator\n",
          "retcode": 0
        },`

I've not changed anything yet, I had to add an extra parameter to `tox` like this:
`tox --result-json=results.json`
Does it look good?
Still need to figure out how to make that docker-compose start tox with that parameter.

**Comment by PawelLipski** [comment]
For the sake of experiment... pls first check if a file in such format will be properly consumed by CircleCI. You can just add a step into `.circleci/config.yml` that would simply save the above JSON in a file, and then call `store_test_results`, as in the sister project's CI config: https://github.com/VirtusLab/git-machete-intellij-plugin/blob/develop/.circleci/config.yml#L58

What you should get in CircleCI should be similar to e.g. https://app.circleci.com/pipelines/github/VirtusLab/git-machete-intellij-plugin/4273/workflows/86e00fbb-1382-4eca-8ebc-3ccd4cc74184/jobs/4492/tests: 

![image](https://user-images.githubusercontent.com/3383210/151051705-1856a389-eddb-4a30-88ae-4edea36fa82d.png)
