### ISSUE TITLE
Use namedtuple instead of tuple in `Hash_ShortHash_Message = Tuple[str, str, str]`

### ISSUE THREAD

**Issue by amalota** [PawelLipski/git-machete#390]
I know that type name: `Hash_ShortHash_Message` has field names in it but it gets lost along the way and it can be easier and cleaner to use namedtuple.
e.g.

change this:
`        

        commits: List[Hash_ShortHash_Message] = self.__git.get_commits_between(
            opt_fork_point, current_branch)

        if not commits:
            raise MacheteException(
                "No commits to squash. Use `-f` or `--fork-point` to specify the "
                "start of range of commits to squash.")

        if len(commits) == 1:
            sha, short_sha, subject = commits[0]
            print(f"Exactly one commit ({short_sha}) to squash, ignoring.\n")
            print("Tip: use `-f` or `--fork-point` to specify where the range of "
                  "commits to squash starts.")
            return`

to this:
`        

        if len(commits) == 1:
            print(f"Exactly one commit ({commits[0].short_sha}) to squash, ignoring.\n")
            print("Tip: use `-f` or `--fork-point` to specify where the range of "
                  "commits to squash starts.")
            return`

**Comment by PawelLipski** [comment]
Done with #392
