### ISSUE TITLE
Add git-machete to official Homebrew package collection

### ISSUE THREAD

**Issue by PawelLipski** [PawelLipski/git-machete#414]
So that it's no longer needed to add a tap.

**Comment by PawelLipski** [comment]
Already attempted 2+ years ago: https://github.com/Homebrew/homebrew-core/pull/48238, wasn't accepted back then... before another attempt, let's see what other git plugins similar to git-machete are already included (how many stars on github they've got etc.).

**Comment by PawelLipski** [comment]
One example is https://github.com/Homebrew/homebrew-core/blob/master/Formula/git-plus.rb ... https://github.com/tkrajina/git-plus has 170 stars, last release in 2017 😅

**Comment by PawelLipski** [comment]
In the PR, would be good to mention independently-written blog posts on git-machete: 
* https://benjamincongdon.me/blog/2022/07/17/In-Praise-of-Stacked-PRs/
* https://dev.to/morrone_carlo/hidden-gems-5-jetbrains-plugins-to-boost-your-productivity-1728 (that's about IntelliJ plugin, though)

**Comment by PawelLipski** [comment]
TBD how updating the version will then look like... will we need to open a PR to `Homebrew/homebrew-core` with every release (just as we commit to [VirtusLab/homebrew-git-machete](https://github.com/VirtusLab/homebrew-git-machete) now)?

I suppose there's some automation to keep Homebrew in sync with PyPI, there're surely hundreds of such Homebrew packages (which are just mirrors of a PyPI package).

**Comment by amalota** [comment]
@PawelLipski Here we go -> https://github.com/Homebrew/homebrew-core/pull/111891
