### ISSUE TITLE
Should `git machete github checkout-prs --by=...` switch current branch when >1 PR is checked out?

### ISSUE THREAD

**Issue by PawelLipski** [PawelLipski/git-machete#437]
Repro (for the state of this repo as of Tue 15 Feb 16:36:18 CET 2022):

1. remove local branches `cli/checkout_prs_zsh_bash_completion` and `feature/command_clean`
2. remove the references to them from .git/machete if they were present there
3. `git machete github checkout-prs --by=amalota`

What happens is that the current branch is switched to one of the PRs:

```
(current branch: develop)

$ git machete github checkout-prs --by=amalota
branch 'cli/checkout_prs_zsh_bash_completion' set up to track 'origin/cli/checkout_prs_zsh_bash_completion'.
Switched to a new branch 'cli/checkout_prs_zsh_bash_completion'
Pull request #416 checked out at local branch cli/checkout_prs_zsh_bash_completion
branch 'feature/command_clean' set up to track 'origin/feature/command_clean'.
Switched to a new branch 'feature/command_clean'
Pull request #435 checked out at local branch feature/command_clean

(current branch: feature/command_clean)
```

Is that expected?

**Comment by PawelLipski** [comment]
Esp. that docs say `If only one PR is given, then switch the local repository's HEAD to its head branch.`

Would be good to make it more precise: `only one PR number`, since now it might give an impression that it applies e.g. also in the case when you provide `--by=...` for an author that has a single PR opened

EDIT: actually... I've used the option `--by` a few times so far, and I think switching to the PR if there's just one PR by the given author is a pretty nice UX 🤔

**Comment by amalota** [comment]
Changed to `If only one PR is checked out, then switch the local repository's HEAD to its head branch`, which means that no matter the options, if at the end one PR is being checked out, only then branch switch takes place.
