### ISSUE TITLE
For what tox envs is `testenv:` prefix actually needed?

### ISSUE THREAD

**Issue by PawelLipski** [PawelLipski/git-machete#446]
AFAICS the fact that docs are rendered within `testenv:docs` tox env causes it to install `pytest` to `docs` venv... which is probably redundant. To be researched.

**Comment by amalota** [comment]
It doesn't work like that, docs env overrides `deps` ,and `commands` sections of base `testenv` so pytest doesn't get installed nor does it get executed, as per https://tox.wiki/en/latest/config.html:

<img width="1288" alt="image" src="https://user-images.githubusercontent.com/86779115/155727345-15c61536-b482-414c-98f7-cd6919ba7815.png">

**Comment by PawelLipski** [comment]
Okay... but is there any good reason for `docs` to inherit `testenv` common at all?

**Comment by PawelLipski** [comment]
Or from other direction, is there a reason why just `flake8` doesn't inherit `testenv` and all other envs do? 🤔

**Comment by amalota** [comment]
@PawelLipski Looks like its NOT possible to execute tests with `tox -e flake8`, as it turns out, you need the prefix `testenv:` for that. Because of that i would consolidate flake8 and pep8 together, since pep8 executes flake8, we don't need both.

**Comment by amalota** [comment]
@PawelLipski I investigated it further and i have seen several solutions like ours, where [flake] section is used to set flake's configurations. As shown below, you can do it both ways, but i think current option is better

![image](https://user-images.githubusercontent.com/86779115/156415888-300ee17d-f4c7-478a-87e7-be0956f52820.png)

(https://flake8.pycqa.org/en/latest/user/configuration.html)

**Comment by PawelLipski** [comment]
Okay... so actually, why do we have 2-level hierarchy with `testenv:pep8` and `flake8`, instead of just either of these?

**Comment by PawelLipski** [comment]
(if it stays like that, pls explain the reason in a comment in tox.ini)

**Comment by amalota** [comment]
@PawelLipski We need `testenv:pep8` to be able to execute tests using `tox`, and we need `flake8` to set configuration options for flake8 command used in `testenv:pep8`

**Comment by PawelLipski** [comment]
Okay! so for clarity... for all envs other than `flake8`, the `testenv` prefix IS needed right?
