### ISSUE TITLE
Disable (but not remove) Github webhook for snapcraft.io

### ISSUE THREAD

**Issue by PawelLipski** [PawelLipski/git-machete#465]
Disable it before the release of v3.8.0. Don't remove since it might be still useful if things go awry.

**Comment by amalota** [comment]
@PawelLipski Disconnect? 
![image](https://user-images.githubusercontent.com/86779115/157668260-da4eabc2-7af3-4482-8317-5f2b89aab942.png)

**Comment by PawelLipski** [comment]
Hmmm I'd apply as light-handed and **easily reversible** approach for the start... hence the suggestion to just disable the GitHub webhook 🤔 but once the new build strategy is tested on v3.8.0, disconnecting the repo from Snap Store could be the next (final?) step

**Comment by amalota** [comment]
@PawelLipski I can't find the option to disable it. Can you do it if you know where it is?

**Comment by PawelLipski** [comment]
https://github.com/VirtusLab/git-machete/settings/hooks/302884141 -> 
![image](https://user-images.githubusercontent.com/3383210/157690702-f9a38144-8187-4f8e-a3e3-656933e0a609.png)

Done!
