### ISSUE TITLE
git_operations.py should be as machete-agnostic as possible

### ISSUE THREAD

**Issue by PawelLipski** [PawelLipski/git-machete#475]
In particular, I'm not happy about `rebase` calling `machete-pre-rebase` hook, which is a git-machete-specific thing. TBD what else should me moved away from git_operations.py (Ctrl+F for `machete`).

**Comment by AABur** [comment]
@PawelLipski needs clarification.

`machete` is found:

- [`GIT_MACHETE_EDITOR`](https://github.com/VirtusLab/git-machete/blob/a3d86f9667d64181413f78a52124593f35f868f5/git_machete/git_operations.py#L216)
- [`GIT_MACHETE_REBASE_OPTS`](https://github.com/VirtusLab/git-machete/blob/a3d86f9667d64181413f78a52124593f35f868f5/git_machete/git_operations.py#L793)
- [`machete-pre-rebase`](https://github.com/VirtusLab/git-machete/blob/a3d86f9667d64181413f78a52124593f35f868f5/git_machete/git_operations.py#L827)

What's wrong with them?

**Comment by PawelLipski** [comment]
Huh nothing wrong specifically with the above... it's a matter of general design soundness: having well-separated layers so that the lower layers (`git_operations`) don't know anything about the higher layers (`client`, which has Machete-specific stuff). I'd suggest moving methods up to `MacheteClient` and/or passing stuff (`GIT_MACHETE_REBASE_OPTS`?) as parameters to `git_operations` methods
