### ISSUE TITLE
`git machete github anno-prs` doesn't work with custom GitHub URL

### ISSUE THREAD

**Issue by kgadek** [PawelLipski/git-machete#479]
# Overview

I've stumbled upon some issues with GitHub recently: _sometimes_ for _some_ repos, `git push` wouldn't work. With trial-and-error, I found a reliable workaround for me:

```shellsession
$ git remote -v
origin	github:VirtuslabRnD/nfs-core.git (fetch)
origin	github:VirtuslabRnD/nfs-core.git (push)

$ cat ~/.ssh/config
Host github
    Hostname        ssh.github.com
    Port            443
    User            git
    IdentityFile    ~/.ssh/id_ed25519
    IdentitiesOnly  yes
```

However, this setup breaks branch discovery:
```shellsession
$ git machete github anno-prs -v
git rev-parse --git-dir
git for-each-ref --format=%\(refname\)$'\t'%\(objectname\)$'\t'%\(tree\)$'\t'%\(committerdate:raw\) refs/remotes
git for-each-ref --format=%\(refname\)$'\t'%\(objectname\)$'\t'%\(tree\)$'\t'%\(committerdate:raw\)$'\t'%\(upstream\) refs/heads
git remote
git config --get remote.origin.url
Remotes are defined for this repository, but none of them corresponds to GitHub (see git remote -v for details)
```

## `git` and `git machete` versions

```shellsession
$ git --version
git version 2.35.1

$ git machete --version
git machete version 3.7.2
```

**Comment by PawelLipski** [comment]
Somewhat related to https://github.com/VirtusLab/git-machete/issues/137, although it's not necessary to fully implement #137 to fix this particular problem. I think the solution could be to provide `machete.github.organization` and `machete.github.repository` config keys that will have precedence over whatever is detected by `git remote`, WDYT?

**Comment by kgadek** [comment]
> I think the solution could be to provide `machete.github.organization` and `machete.github.repository` config keys that will have precedence over whatever is detected by `git remote`, WDYT?

Simple & expectable — makes perfect sense to me 👍

**Comment by PawelLipski** [comment]
We've got quite a lot of stuff to be released in the long-pending v3.8.0... hope you don't mind if we put it into the subsequent v3.9.0, to be released soon after 😅

**Comment by kgadek** [comment]
Nah, that's fine — it's not critical 👍

**Comment by PawelLipski** [comment]
Lemme do a quick _analog telemetry_ while I've got you here: out of 4 existing `git machete github` subcommands (`anno-prs`, `checkout-prs`, `create-prs`, `retarget-prs`), which ones do you use/how often?

```shell
history | grep -Eo 'g(it)? m(achete)? github (anno-prs|checkout-prs|create-pr|retarget-pr)' | cut -d' ' -f4 | sort | uniq -c
```

I assume there'll be at least one occurrence of `anno-prs` in the result ;)

**Comment by kgadek** [comment]
I'm surprised b/c I though I'm using `anno-prs` the most, while in fact:

```
   5 anno-prs
  11 create-pr
```

**Comment by PawelLipski** [comment]
v3.10.0 FTW
