### ISSUE TITLE
Describe hooks usage in README.md

### ISSUE THREAD

**Issue by mkondratek** [PawelLipski/git-machete#499]

**Comment by PawelLipski** [comment]
Hmmm README.md might be too prominent, I don't want to overblow it 🤔 it's available at https://git-machete.readthedocs.io/en/stable/#hooks

**Comment by PawelLipski** [comment]
I suppose you meant intellij-plugin repo as a target for this issue?

**Comment by mkondratek** [comment]
I meant this repo. I understand your pov but for me hooks seem to be a bit hidden feature xd _do what u want_ :woman: 

issue for intellij plugin is required to indeed: https://github.com/VirtusLab/git-machete-intellij-plugin/issues/821

**Comment by PawelLipski** [comment]
It's hidden... and it's also pretty _3rd-echelon_ feature TBH, so to speak 😅 

`machete-pre-rebase` is only useful in certain rare scenarios (mostly like shifting DB migration numbers or version numbers when rebasing)

`machete-post-slide-out` is mostly obsolete, it was useful for retargeting PRs on GitHub... but at certain point in 2020 GitHub started retargeting PRs automatically anyway

`machete-status-branch` is the only one to have some wider usage... mostly for displaying the version in case it's kept **directly in code**, like in git-machete or git-machete-intellij-plugin. But in most project, software version is **derived from git tags** anyway &mdash; which I think is brittle and I don't like it, but just my personal opinion
