### ISSUE TITLE
Does `/pulls` endpoint for a public GitHub repository really require authentication?

### ISSUE THREAD

**Issue by PawelLipski** [PawelLipski/git-machete#506]
As @mkondratek reported:

I've tried to use `create-pr` with that result:

```sh
mikko@mikko-MS-7C91:~/IdeaProjects/git-machete-intellij-plugin$ git machete github create-pr
Fetching origin...
Creating a PR from hook-executors-improvements to develop...Given endpoint: https://api.github.com/repos/VirtusLab/git-machete-intellij-plugin/pulls, not found in GitHub or you don't have the permission to access it (expired token?).
```

I have no token (generated and) set so that's the reason. After that - works.

_Originally posted by @mkondratek in https://github.com/VirtusLab/git-machete/issues/493#issuecomment-1113174706_

---

My addition: note that https://api.github.com/repos/VirtusLab/git-machete-intellij-plugin/pulls can be readily accessed from browser and returns legit results. Let's check why this error happens when accessing GitHub API from git-machete CLI. If this can't be circumvented (e.g. for private repos), let's at least improve the error message (since it doesn't even clearly state that the token might be missing, only mentions expiry) :thinking:

**Comment by amalota** [comment]
@PawelLipski I checked and you can indeed access pulls in the repo using API without token but you can't create PR without one, maybe it's dependent on the HTTP method used (to view pulls i used `GET` but to create PR u need to use `POST`) or sth else, i couldn't find any more information from the docs: https://docs.github.com/en/rest/pulls/pulls#list-pull-requests. To sum up, the scope of this issue should be limited to updating the error message, wdyt?

**Comment by PawelLipski** [comment]
Awww crap, I see now, it was probably `POST /pulls` endpoint that failed in the original error, not `GET /pulls` 🤦🏻 my bad

Okay so pls do two things:
1. improve formatting: `Creating a PR from hook-executors-improvements to develop...Given endpoint: ` looks bad, let's have some newline after `...`
2. include HTTP verb in the error message
