### ISSUE TITLE
per-worktree machete option

### ISSUE THREAD

**Issue by 1wsx10** [PawelLipski/git-machete#517]
﻿https://xkcd.com/1172/

i actually found this very helpful, would be great if there was an option for it.

**Comment by 1wsx10** [comment]
this was fixed here:
https://github.com/VirtusLab/git-machete/pull/361
https://github.com/VirtusLab/git-machete/issues/360

**Comment by PawelLipski** [comment]
Haha I didn't know this xkcd... applies here perfectly indeed 😅 could you provide more details on how your workflows around worktrees look like? even pieces of bash_history could be useful (unless confidential ofc)

**Comment by 1wsx10** [comment]
i have a script that deletes a worktree, and removes local branches that have been merged to the remote and aren't found in any other worktrees.

its also handy for keeping track of which local branches are 'tied' to which worktrees. i know they aren't actually tied but with long builds you generally want to keep a worktree on the same version for as long as possible.

**Comment by PawelLipski** [comment]
Okay! so `machete.worktree.useTopLevelMacheteFile` FTW, I'm putting this issue into the next milestone (v3.10; might end up in v3.11, actually)

**Comment by 1wsx10** [comment]
thats awesome, thanks :)
unfortunately brew deprecated backdating... i guess i'll have to install it manually

**Comment by PawelLipski** [comment]
Whoops (coz I'm a Fedora and not Mac OS/Homebrew user myself, I'm only publishing this package to Homebrew tap)... what does actually  _backdating_ correspond in Homebrew? Is it equivalent to simply downloading newer versions for the already installed software (like `pip install --upgrade` or `dnf update`)?

**Comment by 1wsx10** [comment]
im not entirely sure.. its slow and bloated, but its the package manager that we have...
the most i know is that you can upload separate versions if you want the older versions to be available after the update. otherwise you can only access the latest.

**Comment by 1wsx10** [comment]
https://stackoverflow.com/questions/43538993/homebrew-list-available-versions-with-new-formulaversion-format

they used to support backdating to any old version, but now they have to be specifically created as separate releases i guess

**Comment by PawelLipski** [comment]
> you can only access the latest.

Oh! okay, that's good, no problem then with shipping that feature in v3.10 or v3.11.

I suppose you mentioned

>i guess i'll have to install it manually

for the sake of installing a previous version which has the old logic for worktree's .git/machete location, i.e. v3.6.0 or earlier, right? If so, I'd probably un-install git-machete from Homebrew, and use `pip install git-machete==3.6.0` instead (possibly with `sudo`)

**Comment by 1wsx10** [comment]
ahh yeah ill try it with pip. thanks :)

**Comment by PawelLipski** [comment]
To be released soon in v3.11.0
