### ISSUE TITLE
Create a new help topic (not command!) `git machete help config`

### ISSUE THREAD

**Issue by PawelLipski** [PawelLipski/git-machete#518]
To group all the configs & env vars since there's already quite a few of them:

* `GIT_MACHETE_REBASE_OPTS`
* `machete.github.{remote,organization,repository}` (in progress on @amalota's PR #487)
* `machete.overrideForkPoint.<branch>.{to,whileDescendantOf}`
* `machete.status.extraSpaceBeforeBranchName` (TBD on @amalota's PR #511)
* `machete.worktree.useTopLevelMacheteFile` (??? &mdash; TBD for @1wsx10 issue #517)
* (check if I haven't forgotten anything)

**Comment by 1wsx10** [comment]
Nice! will try when im back at work

**Comment by PawelLipski** [comment]
Not released yet... almost there, stay tuned 👀

**Comment by PawelLipski** [comment]
Okay, released to all channels now as v3.11.1 📦
