### ISSUE TITLE
GitHub create-pr not working on remotes with ssh prefix 

### ISSUE THREAD

**Issue by mkondratek** [PawelLipski/git-machete#531]
```sh
mkondratek@VL-D-1096 git-machete-intellij-plugin % git machete github create-pr
Remotes are defined for this repository, but none of them corresponds to GitHub (see git remote -v for details)

mkondratek@VL-D-1096 git-machete-intellij-plugin % git remote -v
origin  ssh://git@github.com/VirtusLab/git-machete-intellij-plugin.git (fetch)
origin  ssh://git@github.com/VirtusLab/git-machete-intellij-plugin.git (push)
```

**Comment by PawelLipski** [comment]
`git_machete.github.GITHUB_REMOTE_PATTERNS` has `"^git@github\\.com:(.*)/(.*)\\.git$"` currently ☹️

**Comment by amalota** [comment]
@mkondratek How did u end up with this prefix?

**Comment by mkondratek** [comment]
I do not remember exactly. Most likely I have been struggling with some connection (internet or GitHub) issues and did set it manually. Some StackOverflow answers suggested that.

**Comment by amalota** [comment]
Well, its a first time i see `ssh://` prefix, as per: https://docs.github.com/en/get-started/getting-started-with-git/managing-remote-repositories it should be 
https -> `https://github.com/USERNAME/REPOSITORY.git` 
ssh -> `git@github.com:USERNAME/REPOSITORY.git`
This is such a special case, i am not 100% convinced we should change `git_machete.github.GITHUB_REMOTE_PATTERNS` just for this, wdyt @PawelLipski?

**Comment by PawelLipski** [comment]
TBH I was pretty surprised as well, never seen explicit `ssh://` scheme in SSH URLs... but it shouldn't harm to include that in the patterns, so YOLO, I'd proceed

**Comment by mkondratek** [comment]
My thinking is like... it is ok for github - it should be ok for git machete too 😄
