### ISSUE TITLE
`git machete` bash completions does not work for many commands and subcommands

### ISSUE THREAD

**Issue by amalota** [PawelLipski/git-machete#542]
**Commands**
Completion doesn't work (prompts file names or doesn't prompt anything at all) for all commands except `github`.

**Subcommands**
Completion doesn't work (prompts file names or doesn't prompt anything at all) for subcommands such as:
- anno --branch=|-b
- add  --onto=|-o
- discover --checked-out-since=|-C
- fork-point --override-to=
- reapply --fork-point=|-f
- slide-out --down-fork-point|-d
- squash --fork-point=|-f
- update --fork-point=|-f

Completion works for subcommands:
- github checkout-prs --by=
- status --color=
- traverse --return-to=|--start-from=

**Comment by PawelLipski** [comment]
> Completion doesn't work (prompts file names or doesn't prompt anything at all) for subcommands such as:
> 
> * anno --branch=|-b

`anno -b <TAB>`, `anno --branch <TAB>`, `anno --branch=<TAB>`  all work
`anno -b=<TAB>` doesn't work (suggests file names)

> * add  --onto=|-o

As with `anno`, just `-o=<TAB>` is broken

> * discover --checked-out-since=|-C

Yeah, filenames shouldn't be suggested but they are, for every combination

> * fork-point --override-to=

Okay, both with `=` and without

> * reapply --fork-point=|-f

Ok

> * slide-out --down-fork-point|-d

Ok 

> * squash --fork-point=|-f

Ok

> * update --fork-point=|-f

Ok


> Completion works for subcommands:
> 
> * github checkout-prs --by=
> * status --color=
> * traverse --return-to=|--start-from=

Confirming.

**Comment by PawelLipski** [comment]
So slightly different results in my bash 😅
