### ISSUE TITLE
`snapcraft`: `--with is no longer supported, export the auth to the environment variable 'SNAPCRAFT_STORE_CREDENTIALS' instead`

### ISSUE THREAD

**Issue by PawelLipski** [PawelLipski/git-machete#557]
See the logs of e.g. https://app.circleci.com/pipelines/github/VirtusLab/git-machete/2171/workflows/54137532-fc50-445e-bed5-d9d84b936264/jobs/10118.

By _no longer supported_ they seem to really mean _deprecated_, coz the pipeline still passed. Anyway, a migration would be a good idea 😅

Here someone reported that their CI **failed** for that reason 😯 https://github.com/certbot/certbot/issues/9323

**Comment by amalota** [comment]
@PawelLipski Hmm 🤔, i think this option is bugged, see: https://app.circleci.com/pipelines/github/VirtusLab/git-machete/2275/workflows/0789426d-eecf-4650-9fa1-3a9fc0588f44/jobs/10739 also there is a similar bug already reported

**Comment by PawelLipski** [comment]
> also there is a similar bug already reported

Could you provide a link to the bug?

**Comment by amalota** [comment]
> > also there is a similar bug already reported
> 
> Could you provide a link to the bug?

Here's the link to the bug https://bugs.launchpad.net/snapcraft/+bug/1980534, looks like in last days it changed its status to confirmed

**Comment by PawelLipski** [comment]
Whoops okay, let's just keep the issue afloat, revisit in a few weeks

**Comment by PawelLipski** [comment]
Update: the bug is Triaged but still Unassigned
