### ISSUE TITLE
Gif in README is too fast (?)

### ISSUE THREAD

**Issue by PawelLipski** [PawelLipski/git-machete#560]
Too much text appears, I tried to show the gif as a demo to my folks and couldn't keep up with what happens 😅

**Comment by PawelLipski** [comment]
To be assessed once more.. maybe too fast to comment on a live demo, but just okay to capture the attention of the newcomers (which is the primary goal, more important than the demos)?

Or to cater for both needs... replace unpausable gif with a pausable video? TBD:
* if this is a reasonable/common practice in github readmes
* if asciinema can generate mp4 or whatnot videos directly (or conversion from gif is needed)

**Comment by amalota** [comment]
@PawelLipski I think it is indeed to fast, even for newcomers, i think we should slow it down, i'll make a PR for this

**Comment by PawelLipski** [comment]
(leaving as open until #670 is done)
