### ISSUE TITLE
Subtask of #552: `machete {status, discover, traverse}` assumes only one remote for branch and doesn't take branch tracking data into account

### ISSUE THREAD

**Issue by amalota** [PawelLipski/git-machete#561]
When `machete {status, discover}` resolves the branch status in relation to remote it assumes that there is only one remote and uses function `get_strict_remote_for_fetching_of_branch` which returns the remote that was added last.

We need to figure out the logic for what to do when the branch X is present in multiple remotes.

**Comment by PawelLipski** [comment]
Closed? 🤔 
Assuming it's been by mistake, re-close if it was intentional

**Comment by PawelLipski** [comment]
Oh! I see, https://github.com/VirtusLab/git-machete/issues/563 FTW; this one isn't valid indeed
