### ISSUE TITLE
`git machete` functions for resolving remote of a branch or a branch's remote counterpart assume that a branch is only present in one remote 

### ISSUE THREAD

**Issue by amalota** [PawelLipski/git-machete#562]
# Functions:

### `get_strict_remote_for_fetching_of_branch`

```   
 def get_strict_remote_for_fetching_of_branch(self, branch: LocalBranchShortName) -> Optional[str]:
        remote = self.get_config_attr_or_none(f"branch.{branch}.remote")
        return remote.rstrip() if remote else None
```
**-> returns only one remote, the one that was added last**

Used by commands:
- `discover`
- `status`
- `traverse`
- `github create-pr` through the `__sync_before_creating_pr` function

### `get_inferred_remote_for_fetching_of_branch`
```
    def get_inferred_remote_for_fetching_of_branch(self, branch: LocalBranchShortName) -> Optional[str]:
        # Since many people don't use '--set-upstream' flag of 'push', we try to infer the remote instead.
        for remote in self.get_remotes():
            if f"{remote}/{branch}" in self.get_remote_branches():
                return remote
        return None
```
**-> returns only one remote, the first one that meets the requirements from alphabetically ordered remote-branch pairs**

Used by commands:
- `discover`
- `status`
- `traverse`
- `github create-pr` through the `__sync_before_creating_pr` function

### `__get_inferred_counterpart_for_fetching_of_branch`
```
    def __get_inferred_counterpart_for_fetching_of_branch(self, branch: LocalBranchShortName) -> Optional[RemoteBranchShortName]:
        for remote in self.get_remotes():
            if f"{remote}/{branch}" in self.get_remote_branches():
                return RemoteBranchShortName.of(f"{remote}/{branch}")
        return None
```
**-> returns only one local branch remote counterpart, the first one that meets the requirements from alphabetically ordered remote-branch pairs**

Used by commands:
- `list`
- `add`
- `up`
- `discover`
- `status`
- `traverse`
- `advance`
- `fork-point`
- 
### `get_strict_counterpart_for_fetching_of_branch`
```
    def get_strict_counterpart_for_fetching_of_branch(self, branch: LocalBranchShortName) -> Optional[RemoteBranchShortName]:
        if self.__counterparts_for_fetching_cached is None:
            self.__load_branches()
        return self.__counterparts_for_fetching_cached.get(branch)
```
**-> returns only one local branch remote counterpart,, the one that was added last**

Used by commands:
- `github create-pr` through the `__sync_before_creating_pr` function
- `add`
- `up`
- `discover`
- `status`
- `traverse`
- `advance`
- `fork-point`

**Comment by PawelLipski** [comment]
Hmmm if it comes to `get_strict_...` methods... it is intended that they always point to a single remote! that's basically how the underlying branch tracking model works in git.

The problem is however with `get_inferred_...` variants &mdash as explained on https://github.com/VirtusLab/git-machete/issues/563

**Comment by amalota** [comment]
> Hmmm if it comes to `get_strict_...` methods... it is intended that they always point to a single remote! that's basically how the underlying branch tracking model works in git.
> 
> The problem is however with `get_inferred_...` variants &mdash as explained on #563

I just realised that when we have branch tracking data,  in most cases, functions: `get_combined_counterpart_for_fetching_of_branch` or `get_combined_remote_for_fetching_of_branch` get used to resolve remote and in their logic they first try to use branch tracking data so the `strict` methods would get used and even if there were multiple remotes associated with the branch it would return only one (the one added last) and the `infer` remote methods would not even get the chance to be used.

```
    def get_combined_counterpart_for_fetching_of_branch(self, branch: LocalBranchShortName) -> Optional[RemoteBranchShortName]:
        # Since many people don't use '--set-upstream' flag of 'push' or 'branch', we try to infer the remote if the tracking data is missing.
        return self.get_strict_counterpart_for_fetching_of_branch(branch) or self.__get_inferred_counterpart_for_fetching_of_branch(branch)
```

```
    def get_combined_remote_for_fetching_of_branch(self, branch: LocalBranchShortName) -> Optional[str]:
        # Since many people don't use '--set-upstream' flag of 'push', we try to infer the remote instead if the tracking data is missing.
        return self.get_strict_remote_for_fetching_of_branch(branch) or self.get_inferred_remote_for_fetching_of_branch(branch)
```

The current logic doesn't sit well with me, i guess i would first check if there is only one remote associated with the branch and if so then used the current logic (`strict` method first, if missing then `infer`) but if not then used `infer` method? or if it is possible to check if there are multiple remotes associated with the branch directly in branch tracking data and if there are -> return None? @PawelLipski wdyt?

**Comment by PawelLipski** [comment]
As discussed in person:

> The current logic doesn't sit well with me, i guess i would first check if there is only one remote associated with the branch and if so then used the current logic (strict method first, if missing then infer) but if not then used infer method?

The current logic is how git generally reasons about remote tracking branches: if there is a `branch.<...>.remote` config, it is taken as the **source of truth**.

Otherwise (if **not** treated as the source of trurth), `branch.<...>.remote` config would make little sense:
* if there's only one matching branch in remote(s), then config would be redundant (coz we know the matching remote already)
* if there's more than one matching branch in remotes, then we would effectively ignore the config :/

The point of the `branch.<...>.remote` config is precisely to point to the correct remote, even if there is more than one matching remote!
