### ISSUE TITLE
Subtask of #562: `get_inferred_remote_for_fetching_of_branch`  -> returns only one remote, the first one that meets the requirements from alphabetically ordered remote-branch pairs

### ISSUE THREAD

**Issue by amalota** [PawelLipski/git-machete#563]
Subtask of #562

**Comment by PawelLipski** [comment]
This is different from behavior of e.g. `git checkout foo` (when there's no local `foo` branch): `git checkout foo` will only create local `foo` out of `<remote>/foo` only if there's exactly **one** `<remote>` with a `foo` branch

**Comment by PawelLipski** [comment]
We should probably just return nothing from `get_inferred_remote_for_fetching_of_branch` if there's **more than one** remote with the given `branch`
