### ISSUE TITLE
Check the state of git-machete conda package

### ISSUE THREAD

**Issue by PawelLipski** [PawelLipski/git-machete#584]
https://anaconda.org/conda-forge/git-machete

Does it install correctly on Mac/Linux?

Maybe worth:
* mentioning in README.md as a way to install
* adding a badge to README.md

**Comment by PawelLipski** [comment]
Also, can we claim ownership of this package in any way? It seems to be auto-mirrored from PyPI... I've only learnt about it today 😅

**Comment by amalota** [comment]
Yes, i just checked and the package does correctly install on Mac OS.

**Comment by amalota** [comment]
> Also, can we claim ownership of this package in any way? It seems to be auto-mirrored from PyPI... I've only learnt about it today 😅

Do you know if VirtusLab has an official account on anaconda.org?

**Comment by PawelLipski** [comment]
> Do you know if VirtusLab has an official account on anaconda.org?

Huh @zkrolikowski-vl do you know anything about that? 🤔

**Comment by zkrolikowski-vl** [comment]
There isn't anything like an official Virtuslab account on anaconda.org

You should claim maintainership of this repository: https://github.com/conda-forge/git-machete-feedstock

Just create a PR according to this https://conda-forge.org/docs/maintainer/adding_pkgs.html#recipe-maintainer describing the problem and the current maintainer who is from anaconda team should get a notification.

**Comment by PawelLipski** [comment]
Already done a while ago, we've claimed ownership already
