### ISSUE TITLE
Don't use formatting codes when output is not a terminal

### ISSUE THREAD

**Issue by larsks** [PawelLipski/git-machete#595]
# Overview

I just discovered `git machete`. The very first thing I did was run `git machete` by itself to see the help output, but it was much larger than a screenful of text, so I tried:

```
git machete | less
```

And it barfed terminal control codes all over my screen.

## Expected behavior/command output

I expect to be able to pipe help output into a pager  without having to deal with visible escape codes.

## Actual behavior/command output

See bove

## `git` and `git machete` versions

```
git version 2.35.3
git machete version 3.11.3
```

**Comment by PawelLipski** [comment]
Whoops indeed! Thanks for reporting, we'll get that fixed soon 😅

**Comment by PawelLipski** [comment]
In the meantime... you can use `git machete | less -r` to for `less` to correctly interpret ANSI escape codes!
