### ISSUE TITLE
Wire up a linter that would detect would-be interpolated strings that lack the leading `f` 

### ISSUE THREAD

**Issue by PawelLipski** [PawelLipski/git-machete#612]
Such cases were common in the codebase, most notably in one user-facing message:

```
git_machete/client.py:1627:                "Consider running:\n  `git machete fork-point --unset-override {branch}`\n"))
```

I've used some basic regexes to find them, but they spit out a lot of false positives, so they aren't suitable for CI:
```
git grep -En "(^|[^f])'[^']*\{[^']+\}[^']*'" -- '*.py'
git grep -En '(^|[^f])"[^"]*\{[^"]+\}[^"]*"' -- '*.py'
```

Maybe there's some standard linter tool that would capture such cases with less false positives? and where uninterpolated `{...}` are really needed (e.g. in git revs like `HEAD@{tree}`), they could be marked with some `# noqa`

**Comment by PawelLipski** [comment]
See #613

**Comment by AABur** [comment]
Perhaps `flake8` plugin [flake8-use-fstring](https://github.com/MichaelKim0407/flake8-use-fstring#--enable-extensionsfs003-and---fstring-ignore-format) can help solve this problem

If no one else will do it, I can do it in a week

**Comment by PawelLipski** [comment]
That would be great 🙏🏻

**Comment by AABur** [comment]
It's a very simple update - two files need changing:

requirements.pep8.txt
```
	flake8==5.0.4
+ 	flake8-use-fstring==1.4
```

tox.ini
```
	[testenv:pep8]
	deps =
		-r{toxinidir}/requirements.pep8.txt
-	commands = flake8
+	commands = flake8 --enable-extensions=FS003
```
Now we must decide how to use the f-string in code with errors like FSxxx

If nobody minds, I'll modify the code to use f-string where it's not a problem.
We'll discuss the rest in this thread.

**Comment by PawelLipski** [comment]
Ok! Pls proceed... there's probably gonna be a bunch of false positives here and there, but I assume they can be `#noqa`ed out

**Comment by AABur** [comment]
I have implemented what I suggested. Please do a PR review. I may recommend extending f-string to the rest of the code in the future.
