### ISSUE TITLE
Config keys for default settings for subcommands

### ISSUE THREAD

**Issue by sashaweiss-signal** [PawelLipski/git-machete#645]
Hi! Firstly, thanks for maintaining `git-machete` :)

Is it possible to configure "default settings" for subcommands? Specifically, I want to ensure that I never push by default, and rather than remembering `--no-push` every time, it'd be great to have that in my `.gitconfig`.

Thanks in advance for your advice!

**Comment by PawelLipski** [comment]
Hey there... no such feature as for now, but we can cook something up 🧑‍🍳 How about `machete.traverse.push` git config, with the `true` default, that can be overridden to `false`?

**Comment by PawelLipski** [comment]
WDYT @sashaweiss-signal ? ☝🏻

**Comment by sashaweiss-signal** [comment]
Hi sorry, I missed this! (Needed to reconfigure some Github Notifications settings 🙄)

Something like that sounds great to me.

**Comment by PawelLipski** [comment]
Lemme move to v3.13.0 milestone (as per semver, v3.12.1 will be purely about internal implementation fixes etc.)...

**Comment by amalota** [comment]
@PawelLipski Lets hold on with this one until https://github.com/VirtusLab/git-machete/issues/709 is resolved since it can impact it.

**Comment by PawelLipski** [comment]
To be released soon within v3.13.0 📦

**Comment by sashaweiss-signal** [comment]
@PawelLipski, just wanted to say that I've been using this for a stack of 5+ PRs I had for a recent project, and it's been a huge timesaver. Thanks for maintaining :)

**Comment by PawelLipski** [comment]
Great <3 pls spread the word! and contributors (even juniors for [entry-level tasks](https://github.com/VirtusLab/git-machete/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) etc.) are always welcome 🤗
