### ISSUE TITLE
Add automatic docs text formatting which splits the lines based on max line length 

### ISSUE THREAD

**Issue by amalota** [PawelLipski/git-machete#652]
When generating python docs, the new lines formatting in .rst documentation is being omitted which sometimes results in very long lines which are not well readable in terminal and are separated randomly (sometimes in the middle of the word) when the line exceeds some limit.

e.g. for `traverse` command:

![image](https://user-images.githubusercontent.com/86779115/191513818-fe2c29bf-9896-43ac-b1ba-85bf053faa8e.png)

**Comment by PawelLipski** [comment]
Huh definitely to be fixed soon... note that here some 3rd party library (and not just Python stdlib) can be used, as this is a problem with doc generation (and not within the shipped package itself, where we avoid deps at all costs).

**Comment by PawelLipski** [comment]
Actually AFAICS @amalota this is solely the problem with option help right?

**Comment by amalota** [comment]
@PawelLipski Yes

**Comment by PawelLipski** [comment]
Actually... maybe that's not that bad, my GNOME terminal wraps it reasonably. How about you Mac @amalota, what terminal do you use and how does the text look like? As long as it's wrapped on major terminals (and doesn't enable horizontal scrolling), we're good to postpone it until later

**Comment by PawelLipski** [comment]
Also, maybe a better idea to deal with the problem of unbroken options descriptions is to put some **HTML-invisible characters/tags** in .rst, to signify line breaks for Python docs. They won't be rendered/visible in HTML, but will be picked up by the HTML->Python converter 🤔

**Comment by amalota** [comment]
> 

@PawelLipski I am using **iTerm** with **ZSH** and for example docs for traverse command looks like this:
![image](https://user-images.githubusercontent.com/86779115/192285868-33a796f4-6105-4fed-a15e-5164ccb9ac1e.png)

I just realised that the **options** could be indented better (indent not only for the first line of the description but the whole description), so because of that i would postpone this PR until this is fixed in https://github.com/VirtusLab/git-machete/issues/658 and then come back to it, wdyt?

**Comment by PawelLipski** [comment]
> postpone this PR until this is fixed in https://github.com/VirtusLab/git-machete/issues/658 and then come back to it, wdyt?

+1, good idea
