### ISSUE TITLE
[Question] How to traverse only parents and children of the current branch

### ISSUE THREAD

**Issue by antoinewdg-netapp** [PawelLipski/git-machete#656]
First, thanks for this awesome tool, this has made my dev workflow incredibly smooth!
Second, sorry if this is not the right place to ask question, but I could not find any link to a place dedicated to questions.

Let's say I have the following branch layout:

```
main
  feature-a
    bugfix-a
    feature-b
  refactor
  feature-c
```

I there a way, when on `feature-a`, to do `git machete traverse` on:

- `main`
- `feature-a`
- `bugfix-a`
- `bugfix-b`
- but *not* `refactor` and `feature-c`

?

My use case is that I ususally have my main stack of branches I'm currently working on (here that would be `feature-a`, `bugfix-a` and `feature-b`), and other longer-term branches that are not super urgent, and that I work on from time to time. Constantly rebasing and pushing the side branches when working on the main stack is a waste of time and triggers unnecessary CI builds, so I'd like to avoid that.

If my specific idea is not doable right now, is there something else you would suggest? Or a change in my workflow?

Thanks in advance!

**Comment by PawelLipski** [comment]
Hey @antoinewdg-netapp, thanks for kind words!

You're not the first one to come up with that idea ;) https://github.com/VirtusLab/git-machete/issues/293 seems to be about the same idea as well... pls see if that would satisfy your needs and if so, which of the suggested approaches looks most palatable to you 🕵🏻

**Comment by antoinewdg-netapp** [comment]
Hi @PawelLipski .

Thanks for your answer! If I'm not mistaken, #293 is not exactly the same use case. In my case, the other branches are mine, and I would want to use `git machete traverse` on them some times.


A couple of facts about my situation:

-  I need to always have an up-to-date `main` because I'm working on a repo that does not allow merging branches that are no up-to-date with `main` (but even without the hard restriction frequently rebasing on a recent version of `main` is something I would do)
- Before using git machete, I did not even have a local version of `main`, and mostly did `git rebase origin/main`.

My current workflow is to either:

- `git checkout main`
- `git pull --rebase`
- `git checkout feature-a`
- `git machete traverse`

Or `git machete -w -F` and manually say no to all branches not children of `feature-a`.


And I guess I'd like to know a way to do that in one go. 

The reason I'm asking is not necessarily because I'd like to see a feature implementing that land in git machete. It's more that I feel I'm using the tool in the wrong way and/or missing a piece of information.

**Comment by PawelLipski** [comment]
Okay so lemme address the points also from your previous comment:

 > My use case is that I usually have my main stack of branches I'm currently working on (here that would be feature-a, bugfix-a and feature-b), and other longer-term branches that are not super urgent, and that I work on from time to time.

Heh I recognize my own pattern of work in that as well ;D actually, I'd sometimes even move the long-term branches directly after `main` and only start the traversal (with**out** `--whole` option) from the first short-term branch... but still, that doesn't feel like a proper solution, just a workaround

> https://github.com/VirtusLab/git-machete/issues/293 is not exactly the same use case. In my case, the other branches are mine, and I would want to use git machete traverse on them some times.

Actually, lemme rename the issue itself; it shouldn't specifically refer to branches **controlled by someone else**. Indeed, the feature should be just about **not rebasing** and/or **not pushing** the selected branches, whatever the reason &mdash; whether they're controlled by someone else, or whether they're "long-term" branches.

> Or `git machete traverse -w -F`

This combination of two flags is very common, it's got a shortcut flag of its own: `git machete traverse -W` ;)

> The reason I'm asking is not necessarily because I'd like to see a feature implementing that land in git machete. It's more that I feel I'm using the tool in the wrong way and/or missing a piece of information.

I think the feature(s) to cover our cases (someone else' branches, long-term branches) is long missing from git-machete. To be implemented soon then! I'm adding both this one and #293 to v3.13.0 (next minor milestone), and we'll get that delivered with @amalota 💪🏻

> How to traverse only parents and children of the current branch (the issue title)

Now to the specifics... there are two ways we can address this issue:
1. either implement #293, and thus also provide a way to mark long-term branches as "non-rebasable" (let's call it _exclusions_, TBD)
2. or add a flag like `--subtree-only [<branch>]` or `--descendants-only [<branch>]` to `git machete traverse`, that would do exactly as suggested in the issue title (only walk through the subtree rooted in the current/given branch).

TBH I'd prefer doing (1.) as it's much more powerful. 

There is one subtle problem with (1.) tho: as you stated, you _would want to use git machete traverse on them sometimes_. That's reasonable... but I think for that case a flag like `git machete traverse --ignore-exclusions` (name TBD) could be used, WDYT?

**Comment by antoinewdg-netapp** [comment]
Thanks again for the details answer @PawelLipski .

I  was actually not completely aware of the behavior of `traverse`, i.e. it was not completely clear to me that it started at the current branch and then continued on with the other branches. I actually thought the default behavior was to just traverse the subtree of the current branch, and my question was specifically about how to also traverse the parent branch(es) to make sure all the subtree was as up-to-date as possible.
It's kind of weird that I did not notice my misunderstanding earlier, but if you have only one stack of branches traversing the subtree and the following branches in pre-order is the same thing, so that must by why.

I get why `traverse` does that though: it makes resuming from a previous `traverse` call easier, and you don't have to maintain state, so that's super simple.

> I'd sometimes even move the long-term branches directly after main and only start the traversal

That's a pretty good idea, and I think it'll solve most of my issues, I'll try that thanks!

> This combination of two flags is very common, it's got a shortcut flag of its own

Good to know!


I think both 1. and 2. make a lot of sense. I don't think they are mutually exclusive too, I  could see both coexisting.

For 1., in my specific use case, it would be much more practical to ignore only one specific exclusion rather than all of them: I don't usually start working on all my long term branches at once.

**Comment by PawelLipski** [comment]
> For 1., in my specific use case, it would be much more practical to ignore only one specific exclusion rather than all of them: I don't usually start working on all my long term branches at once.

You'll be able to just pass that `--ignore-exclusions` option, and than (assuming ofc that `--yes` was **not** passed), you can opt-out from rebase/push on these other long-term brances as usual with `N` on keyboard :)

**Comment by antoinewdg-netapp** [comment]
Closing for #293 then, thanks for the discussion!

**Comment by PawelLipski** [comment]
@antoinewdg-netapp see the fresh [v3.14.0](https://github.com/VirtusLab/git-machete/releases/tag/v3.14.0) release, which added `rebase=no` and `push=no` branch qualifiers 📦

**Comment by antoinewdg-netapp** [comment]
Awesome, thanks for the heads up!
