### ISSUE TITLE
Once git-machete is available in homebrew-core, replace the current code for updating the tap

### ISSUE THREAD

**Issue by PawelLipski** [PawelLipski/git-machete#665]
- [x] Let's use `brew bump-formula-pr`, as suggested in https://github.com/Homebrew/homebrew-core/pull/111891#issuecomment-1261109350 instead. Worth checking what the linked Github Action does (even though we're not gonna use it, as we run on CircleCI).
- [x] README.md for installation via Homebrew
- [x] CONTRIBUTING.md about post-release steps
- [x] RELEASE_NOTES.md to mention the availability of the package via homebrew-core (as opposed to a tap)
- [x] Archive (**not** delete) [VirtusLab/homebrew-git-machete](https://github.com/VirtusLab/homebrew-git-machete) repo

**Comment by PawelLipski** [comment]
One more thing to be checked: if folks already have git-machete installed from the tap, will `brew` still pull updates from the tap, or from the core package? I unfortunately assume the ~latter~ **EDIT: former**, which means that we'll still need to bump the tap (so that people who originally installed from tap, aren't forever stuck at 3.12.0)

**Comment by PawelLipski** [comment]
(@amalota I've updated the comment above significantly ☝🏻)

**Comment by amalota** [comment]
@PawelLipski I see, in order to make sure how the update process would look like i asked about it here: https://github.com/orgs/Homebrew/discussions/3712

**Comment by PawelLipski** [comment]
Actually, one more thing... for the sake of testing the transition tap->core on v3.12.1, wouldn't it make more sense to:
1. publish v3.12.1 only to core (e.g. via manually running `brew bump-formula-pr` from local machine) and **not** publish v3.12.1 to tap (by commenting out some lines from CI config/scripts)

than to

2. publish v3.12.1 only to tap and not to core (as was the case for the last couple of years)

❓

Then we can apply the procedure suggested in [your Homebrew discussion](https://github.com/orgs/Homebrew/discussions/3712#discussioncomment-3763961) and see if the tap v3.12.0->core v3.12.1 transition really occurs on a few users' machines.

WDYT?

**Comment by amalota** [comment]
@PawelLipski Ok, i like this approach, but if we want to publish v3.12.1 via `brew` core we still have to release v3.12.1 but the current 3.12.1 includes `tap` version update, so we would have to remove it via new PR.  Or where you thinking about publishing v.3.12.1 via `brew` without actually releasing it?

**Comment by PawelLipski** [comment]
> but the current 3.12.1 includes tap version update, so we would have to remove it via new PR

Discussed, indeed removal will be needed before the release v3.12.1 is done
