### ISSUE TITLE
Replace `asciicast2gif` (it is no longer being maintained) with `agg` in `graphics/generate-asciinema-gif`

### ISSUE THREAD

**Issue by amalota** [PawelLipski/git-machete#691]
The replacement is dependent upon fixing a bug in `agg` first-> https://github.com/asciinema/agg/issues/22.

P.S The replacement code is commented out under the TODO text for this issue.

- [ ] Replace the library
- [ ] Update CONTRIBUTING.md

**Comment by PawelLipski** [comment]
The issue is fixed in agg 🎉
