### ISSUE TITLE
`fish` completion suggests files/directories alongside commands

### ISSUE THREAD

**Issue by PawelLipski** [PawelLipski/git-machete#697]
Apparently `-f` in [`complete -c git -n "__fish_git_using_command machete" -f # (suppress file completion)`](https://github.com/VirtusLab/git-machete/blob/v3.12.4/completion/git-machete.fish#L17) doesn't suppress file completion as expected :/

![image](https://user-images.githubusercontent.com/3383210/196147197-82c6ea93-7264-4328-b559-b50b9e76e255.png)

**Comment by PawelLipski** [comment]
Let's check if git-flow completion works as expected: https://github.com/bobthecow/git-flow-completion/blob/master/git.fish and if so, we can use it as a blueprint for patching our existing completion

**Comment by guyboltonking** [comment]
#993 fixes this issue for me; I'd be happy for other people to try it out.

**Comment by PawelLipski** [comment]
Nice! I'll check it later today 👁️

**Comment by PawelLipski** [comment]
Btw @guyboltonking how did you learn of git-machete?

**Comment by guyboltonking** [comment]
> Btw @guyboltonking how did you learn of git-machete?

I was looking for a stacked PR tool; I used machete for a while, then switched to graphite but came back to machete when graphite announced they were going to start charging.

**Comment by PawelLipski** [comment]
Wowow didn't know about graphite charging 😯 btw can you recall the reasons for switching **from machete to graphite** back then?

**Comment by PawelLipski** [comment]
Also, speaking of charging... was there a specific thing in Graphite paid plan that you depended upon?

<img width="694" alt="image" src="https://github.com/VirtusLab/git-machete/assets/3383210/ff1c60af-7bd1-49c5-8d4c-56a494028839">

**Comment by guyboltonking** [comment]
> Wowow didn't know about graphite charging 😯 btw can you recall the reasons for switching **from machete to graphite** back then?

`gt` had pretty much what I needed and was "lighter" than machete, while also having the nice feature of adding a comment linking the stacked PRs on github.  Generally, using `gt` felt like a smoother experience.

I didn't use any of the non-CLI graphite features: I just wanted the CLI for the stacked PRs, the web UI felt awkward.

**Comment by guyboltonking** [comment]
> Also, speaking of charging... was there a specific thing in Graphite paid plan that you depended upon?

10 stacks per org (the free plan limit) is a pretty big non-starter!
