### ISSUE TITLE
Crash when updating untracked branch via traverse

### ISSUE THREAD

**Issue by catherine-yoodli** [PawelLipski/git-machete#742]
# Overview

I wanted to update an untracked local branch with upstream changes from parent branches.

## Expected behavior/command output

Merge `my-parent-branch` into `my-untracked-branch` without errors.

## Actual behavior/command output

```
> git co my-untracked-branch
Switched to branch 'my-untracked-branch'

> git machete traverse --whole --fetch --merge --no-push

[snip successful update of main and my-parent-branch]

Checking out my-untracked-branch

   main
   │
   └─ my-parent-branch
      │
      └─ my-untracked-branch

Merge my-parent-branch into my-untracked-branch? (y, N, q, yq) y
Updating 24d578b66..ce4f5c827
Fast-forward (no commit created; -m option ignored)
 foo.txt | 282 ++++++++++++++++++++++++++++++++++++++++++++++++-------------------------------------------------
 bar.txt |   2 +-
 2 files changed, 142 insertions(+), 142 deletions(-)

Traceback (most recent call last):
  File "/opt/homebrew/bin/git-machete", line 20, in <module>
    cli.main()
  File "/opt/homebrew/Cellar/git-machete/3.13.0/libexec/lib/python3.11/site-packages/git_machete/cli.py", line 857, in main
    launch(sys.argv[1:])
  File "/opt/homebrew/Cellar/git-machete/3.13.0/libexec/lib/python3.11/site-packages/git_machete/cli.py", line 810, in launch
    machete_client.traverse(
  File "/opt/homebrew/Cellar/git-machete/3.13.0/libexec/lib/python3.11/site-packages/git_machete/client.py", line 847, in traverse
    self.__handle_untracked_state(
  File "/opt/homebrew/Cellar/git-machete/3.13.0/libexec/lib/python3.11/site-packages/git_machete/client.py", line 2291, in __handle_untracked_state
    self.handle_untracked_branch(
  File "/opt/homebrew/Cellar/git-machete/3.13.0/libexec/lib/python3.11/site-packages/git_machete/client.py", line 1772, in handle_untracked_branch
    relation: int = self.__git.get_relation_to_remote_counterpart(branch, remote_branch)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/git-machete/3.13.0/libexec/lib/python3.11/site-packages/git_machete/git_operations.py", line 945, in get_relation_to_remote_counterpart
    b_is_anc_of_rb = self.is_ancestor_or_equal(branch.full_name(), remote_branch.full_name())
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/git-machete/3.13.0/libexec/lib/python3.11/site-packages/git_machete/git_operations.py", line 783, in is_ancestor_or_equal
    return self.__get_merge_base(earlier_hash, later_hash) == earlier_hash
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/git-machete/3.13.0/libexec/lib/python3.11/site-packages/git_machete/git_operations.py", line 751, in __get_merge_base
    if hash1 > hash2:
       ^^^^^^^^^^^^^
TypeError: '>' not supported between instances of 'FullCommitHash' and 'NoneType'
```

## `git` and `git machete` versions

```
> git --version
git version 2.38.1

> git machete --version
git machete version 3.13.0
```

**Comment by PawelLipski** [comment]
Thanks for the report, looking into that... the fix should come in the subsequent patch release soon (v3.13.1) 🐞

**Comment by PawelLipski** [comment]
By the way @catherine-yoodli... are you able to share the .git/ folder of the affected repo as a zip? Ofc if it's sth proprietary/NDA-ed then we'll try with what we've got already ;)

**Comment by PawelLipski** [comment]
Or at least the output of `git branch -va`... as I struggle to see the exact set of conditions that could lead to that error 🙏🏻

**Comment by catherine-yoodli** [comment]
> By the way @catherine-yoodli... are you able to share the .git/ folder of the affected repo as a zip? Ofc if it's sth proprietary/NDA-ed then we'll try with what we've got already ;)

Unfortunately, I can't share the .git/ folder for exactly those reasons. Also, I've needed to keep doing my work in this repo, so it's no longer in the same state as before. That said, it's 100% reproducible, so hopefully you can track down the cause!

> Or at least the output of `git branch -va`... as I struggle to see the exact set of conditions that could lead to that error 🙏🏻

As soon as I'm at a lull in my work tasks, I'll get a new repro & the output of `git branch-va` for you! Thanks for the quick response.

**Comment by PawelLipski** [comment]
Wow okay... @amalota if you could take a look right after you're done with #730 (which seems to be very close now!)

**Comment by catherine-yoodli** [comment]
@PawelLipski Hmm, actually, `git branch -va` has a _ton_ of irrelevant branch info, plus commit messages that are also not really relevant at all. What useful info are you hoping to get out of `git branch -va`?

**Comment by PawelLipski** [comment]
Hmmm okay... so if you could at least extract the entries for all branches that contain `my-parent-branch` and `my-untracked-branch` in their names (so also `origin/my-untracked-branch` etc.) 🧐 coz that's what could be important here 🪲
