### ISSUE TITLE
Unify the usage of `@unittest.mock.patch(...)` vs pytest-mock `mocker.patch(...)`

### ISSUE THREAD

**Issue by PawelLipski** [PawelLipski/git-machete#751]
Probably in favor of the latter, TBD.

**Comment by amalota** [comment]
I couldn't really find the reasons why one would be better than the other, so i guess choosing between them is a matter of preference, @PawelLipski should i still go ahead with the latter one?

**Comment by PawelLipski** [comment]
_słuchaj... okej_!
