### ISSUE TITLE
Strict (rather than combined) remote is probably used in too many places

### ISSUE THREAD

**Issue by PawelLipski** [PawelLipski/git-machete#850]
_Strict_ remote is the one pointed by `git config`.
_Inferred_ remote is the one matched by branch name, if present in only one remote (think of `git checkout foo`, when `origin/foo` exists but `foo` not yet).
_Combined_ remote is determined as _strict, or if missing, inferred_.

Methods like `git_machete.git_operations.GitContext.get_strict_remote_sync_status` are used in some unexpected places... like in `traverse`. Probably the `combined` version should be used instead. Let's check if `strict` methods have been used in that places from the very start, or they've been introduced at some point (why?).

Consider making `strict` and `inferred` methods private in `GitContext`. In most (all?) contexts, the `combined` versions should be used to properly account for the cases where vanilla `git push` (with no `-u` flag) have been used.

**Comment by amalota** [comment]
@PawelLipski So method `git_machete.git_operations.GitContext.get_strict_remote_sync_status` was used in the `traverse` from the start.
