### ISSUE TITLE
Use entry_points.txt to declare bin entrypoint, to avoid breaking in venvs

### ISSUE THREAD

**Issue by cspotcode** [PawelLipski/git-machete#919]
# Overview

When installing git-machete globally via pip on Windows, and then working on a python project in a virtualenv, `git machete` fails with a cryptic error: 

```
(.venv) PS C:\Users\cspot\Documents\dev\project> git machete
Traceback (most recent call last):
  File "C:\Users\cspot\scoop\apps\python\current\Scripts\git-machete", line 19, in <module>
    from git_machete import cli
ModuleNotFoundError: No module named 'git_machete'
```

I suspect this is because git-machete does not allow pip to create an `.exe` shim like it does for most other packages.  So `git` runs the `git-machete` script using the venv's `python.exe`, ignoring the shebang.  Thus `sys.path` is still pointing to the virtual env where the `git_machete` module is _not_ installed.

I think the fix is to use `entry_points.txt` to tell pip and other package managers how to create the necessary .exe shim on Windows.

https://packaging.python.org/en/latest/specifications/entry-points/

## Expected behavior/command output

`git machete` works within a virtual env shell, calling out to the globally installed git-machete.

## Actual behavior/command output

The error I pasted above

## `git` and `git machete` versions

```
git --version
git version 2.38.0.windows.1
git machete --version
git machete version 3.17.1
```

## Additional diagnostics info

Here is one way to reproduce this issue on Windows.  Open Powershell:

```
# run in powershell
pip install git-machete
git machete # this should work
mkdir project
cd project
python -m venv .venv
./.venv/Scripts/activate.ps1
git machete # this should fail with the error described above
```

If you modify the `git-machete` script to `print(sys.executable)` you will see that git is executing `git-machete` with the venv's `python.exe`.

**Comment by PawelLipski** [comment]
Wow that was unexpected 😯 any bug reports pertaining to Windows are very appreciated as this platform is relatively  uncommon among the users (and hence, relatively poorly tested) 😅
